const {chromium}=require('/home/user/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('fs');
const base='http://127.0.0.1:3231',out='/tmp/le5-stage1/final-evidence';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch();const results=[],issues=[];try{for(const lang of ['en','es']){const c=await b.newContext({reducedMotion:'reduce'});await c.addCookies([{name:'le5_locale',value:lang,url:base}]);await c.addInitScript(()=>localStorage.setItem('le5.cookie-notice.v1','review'));const p=await c.newPage();p.on('pageerror',e=>issues.push({lang,error:e.message}));
for(const auth of [false,true]){if(auth)await c.request.post(base+'/api/auth',{data:{action:'login',email:'maria@legalenglish5.test',password:'Maria#Alpha26'}});
for(const width of [1440,1024,768,390,320]){await p.setViewportSize({width,height:1000});for(const route of auth?['/dashboard','/terms','/terms/CON-001','/quizzes','/progress','/library','/account','/account/settings','/billing','/account/help']:['/','/about','/pricing','/signup','/login']){await p.goto(base+route,{waitUntil:'networkidle'});const check=await p.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1,height:document.documentElement.scrollHeight,broken:[...document.images].filter(i=>i.offsetWidth&&i.complete&&!i.naturalWidth).map(i=>i.src)}));results.push({lang,width,route,...check});if(check.overflow||check.broken.length)issues.push(results.at(-1));
if(route==='/terms/CON-001')assert.equal(await p.locator('.consideration-photo-band').count(),0);
if(route==='/signup'){assert.equal(await p.locator('.signup-steps li').count(),3);assert.equal(await p.locator('.auth-reference-consent a').count(),3);assert.equal(await p.locator('.auth-reference-terms').count(),0);}
if(route==='/'){assert.equal(await p.locator('main > section').nth(1).getAttribute('id'),'how-it-works');assert.ok(await p.evaluate(()=>document.querySelector('.brief-trust').compareDocumentPosition(document.querySelector('#pricing'))&Node.DOCUMENT_POSITION_FOLLOWING));}
if([390,1440].includes(width)&&['/','/signup','/pricing','/about','/terms/CON-001','/account','/progress'].includes(route))await p.screenshot({path:`${out}/${lang}-${route.replaceAll('/','_')||'home'}-${width}.png`,fullPage:route==='/'});
}console.log(`${lang} ${auth?'learner':'public'} ${width} checked`);}}
await c.close();}fs.writeFileSync(out+'/layouts.json',JSON.stringify({results,issues},null,2));assert.deepEqual(issues,[]);console.log(`Passed ${results.length} layouts without document overflow, broken visible images or browser exceptions.`);}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
