const {chromium}=require('/home/user/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const assert=require('node:assert/strict'), fs=require('fs');const base='http://127.0.0.1:3231',out='/tmp/le5-stage1/evidence';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch();const checks=[];try{for(const lang of ['en','es']){for(const width of [1440,768,390,320]){const c=await b.newContext({viewport:{width,height:1000},hasTouch:width<900,reducedMotion:'reduce'});await c.addCookies([{name:'le5_locale',value:lang,url:base}]);await c.addInitScript(()=>localStorage.setItem('le5.cookie-notice.v1','review'));const p=await c.newPage();p.setDefaultTimeout(10000);const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base,{waitUntil:'networkidle'});
const layout=async(route)=>{assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`overflow ${route} ${lang} ${width}`);assert.equal(await p.locator('img:visible').evaluateAll(a=>a.filter(i=>i.complete&&!i.naturalWidth).length),0);};
await layout('home');assert.equal(await p.locator('main > section').nth(1).getAttribute('id'),'how-it-works');await p.locator('.hero-sample-link').click();await p.waitForTimeout(100);assert.ok(p.url().endsWith('#how-it-works'));assert.ok(await p.locator('.lesson-answers label').count());
if(width===390){await p.goto(base,{waitUntil:'networkidle'});const toggle=p.locator('.landing-menu-toggle');await toggle.click();assert.equal(await p.locator('.home-ref-hero').getAttribute('inert'),'');for(let i=0;i<15;i++){await p.keyboard.press('Tab');assert.ok(await p.evaluate(()=>!!document.activeElement.closest('.landing-nav')),'focus escaped');}await p.keyboard.press('Escape');assert.equal(await toggle.getAttribute('aria-expanded'),'false');assert.ok(await toggle.evaluate(e=>e===document.activeElement),'focus did not return');assert.equal(await p.locator('.home-ref-hero').getAttribute('inert'),null);await toggle.click();await p.setViewportSize({width:1440,height:1000});assert.equal(await toggle.getAttribute('aria-expanded'),'false');assert.equal(await p.locator('.home-ref-hero').getAttribute('inert'),null);await p.setViewportSize({width,height:1000});checks.push(`${lang}: public menu focus, Escape, desktop resize`);}
if(width===1440){for(const path of ['/sample-terms','/how-it-works']){await p.goto(base+path,{waitUntil:'networkidle'});assert.equal(new URL(p.url()).pathname,'/');assert.equal(new URL(p.url()).hash,'#how-it-works');}checks.push(`${lang}: public sample redirects`);}
await p.goto(base,{waitUntil:'networkidle'});await p.screenshot({path:`${out}/${lang}-home-${width}.png`,fullPage:false});
const login=await c.request.post(base+'/api/auth',{data:{action:'login',email:'maria@legalenglish5.test',password:'Maria#Alpha26'}});assert.ok(login.ok());
await p.goto(base+'/terms',{waitUntil:'networkidle'});await layout('terms');const wordBreaks=await p.locator('.terms-category-progress strong').evaluateAll(items=>items.flatMap(el=>{const text=el.firstChild;if(!text||text.nodeType!==3)return [];const s=text.textContent;return [...s.matchAll(/\S+/g)].filter(m=>{const r=document.createRange();r.setStart(text,m.index);r.setEnd(text,m.index+m[0].length);return r.getClientRects().length>1;}).map(m=>m[0]);}));assert.deepEqual(wordBreaks,[],`split category words ${lang} ${width}`);
if(width<861){assert.ok(await p.locator('.learner-tabbar a span').evaluateAll(a=>a.every(e=>e.scrollWidth<=e.clientWidth+1)),'clipped navigation');}
await p.screenshot({path:`${out}/${lang}-terms-${width}.png`,fullPage:false});
await p.goto(base+'/terms/CON-001',{waitUntil:'networkidle'});await layout('lesson');assert.equal(await p.locator('.consideration-ring').count(),0);assert.equal(await p.locator('.lesson-state-steps li[aria-current="step"]').count(),1);await p.locator('.consideration-progress-card').scrollIntoViewIfNeeded();await p.screenshot({path:`${out}/${lang}-lesson-state-${width}.png`,fullPage:false});
if(width===1440){await p.goto(base+'/how-it-works',{waitUntil:'networkidle'});assert.equal(new URL(p.url()).pathname,'/how-it-works');await p.goto(base+'/dashboard',{waitUntil:'networkidle'});const picked=await p.locator('.dashboard-session-list li a').evaluateAll(a=>a.map(e=>({name:e.querySelector('strong').textContent,id:new URL(e.href).pathname.split('/').pop()})));assert.equal(picked.length,5);
await p.locator('.dashboard-session-actions .ghost').click();await p.locator('.session-scope').waitFor();assert.deepEqual(new URL(p.url()).searchParams.get('session').split(','),picked.map(t=>t.id));assert.ok((await p.locator('.quiz-active-topline').innerText()).includes('5'));await p.reload({waitUntil:'networkidle'});assert.ok((await p.locator('.quiz-active-topline').innerText()).includes('5'));await p.locator('.session-scope a').click();
for(let i=0;i<5;i++){await p.waitForURL(u=>u.pathname===`/terms/${picked[i].id}`);await p.waitForFunction(n=>document.querySelector('.consideration-position')?.textContent.includes(n),`${i+1}`);if(i<4)await p.locator('.consideration-term-nav button').nth(1).click();}
await p.locator('.consideration-bottom-actions a[href^="/quizzes?"]').click();const data=await (await c.request.get(base+'/api/bootstrap')).json();
for(let i=0;i<5;i++){await p.waitForFunction(name=>document.querySelector('.quiz-active-card h2 a')?.textContent===name,picked[i].name);const t=data.terms.find(t=>t.id===picked[i].id);const option=t.quiz.correctOption.charCodeAt(0)-65;await p.locator('.quiz-active-options label').nth(option).click();await p.locator('.quiz-active-actions button').last().click();await p.locator('.quiz-correct-row').waitFor();await p.locator('.quiz-active-actions button').last().click();}
await p.locator('.quiz-done').waitFor();assert.ok((await p.locator('.quiz-done').innerText()).includes('100%'));await p.screenshot({path:`${out}/${lang}-session-complete.png`,fullPage:false});checks.push(`${lang}: exact five-term quiz, reload scope, five lesson steps, result and finish`);}
assert.deepEqual(errors,[]);checks.push(`${lang} ${width}: sample, category words, navigation, lesson state, no overflow/errors`);fs.writeFileSync(out+'/checks.json',JSON.stringify(checks,null,2));console.log(checks.at(-1));await c.close();}}}finally{await b.close();}console.log('All stage-one browser checks passed.');})().catch(e=>{console.error(e);process.exit(1)});
