const {chromium}=require('/home/user/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('fs');const base='http://127.0.0.1:3231',out='/tmp/le5-stage1/verification';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch();const checks=[],issues=[];try{for(const lang of ['en','es']){const c=await b.newContext({viewport:{width:390,height:1000},reducedMotion:'reduce'});await c.addCookies([{name:'le5_locale',value:lang,url:base}]);const p=await c.newPage();p.setDefaultTimeout(15000);p.on('pageerror',e=>issues.push(e.message));
await p.goto(base+'/signup?plan=annual',{waitUntil:'networkidle'});assert.equal(new URL(p.url()).searchParams.get('plan'),'annual');await p.locator('.auth-reference-tabs button').first().click();await p.locator('input[type=email]').fill('maria@legalenglish5.test');await p.locator('input[type=password]').fill('Maria#Alpha26');await p.locator('.auth-reference-submit').click();await p.waitForURL('**/billing?plan=annual');checks.push(`${lang}: annual intent survives auth`);
const fixture=await (await c.request.get(base+'/api/bootstrap')).json();let mode='empty';let release;
await p.route('**/api/bootstrap',async route=>{if(mode==='error')return route.fulfill({status:503,body:'Unavailable'});if(mode==='loading')await new Promise(r=>release=r);const data=structuredClone(fixture);if(mode==='empty'){data.terms=[];data.progress=[];data.studyDays=[];}if(mode==='expired'){data.entitlement={allowed:false,label:'Trial expired',detail:'Protected terms stay locked until Mercado Pago restores a valid entitlement.'};data.session.subscription.status='expired';}await route.fulfill({json:data});});
for(const path of ['/dashboard','/terms','/library','/progress']){await p.goto(base+path,{waitUntil:'networkidle'});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.ok(!(await p.locator('body').innerText()).includes('AudioUS'));if(path==='/terms')assert.equal(await p.locator('.terms-empty a[href="/#how-it-works"]').count(),1);if(path==='/progress')assert.equal(await p.locator('.progress-activity-chart').count(),0);await p.screenshot({path:`${out}/${lang}-empty-${path.slice(1)}.png`});}checks.push(`${lang}: empty dashboard, terms, saved library, progress`);
mode='expired';await p.goto(base+'/terms/CON-001',{waitUntil:'networkidle'});assert.equal(await p.locator('.blocked-panel a[href="/billing"]').count(),1);assert.equal(await p.locator('.consideration-detail-stack').count(),0);await p.screenshot({path:`${out}/${lang}-expired.png`});checks.push(`${lang}: expired lesson offers billing recovery`);
mode='error';await p.goto(base+'/terms',{waitUntil:'networkidle'});await p.locator('.sk-error').waitFor();assert.equal(await p.locator('.workspace-skeleton').getAttribute('aria-busy'),'false');assert.ok((await p.locator('.sk-error button').boundingBox()).y<800,'Retry should be visible without scrolling');await p.screenshot({path:`${out}/${lang}-load-error.png`});mode='normal';await p.locator('.sk-error button').click();await p.locator('.terms-card').first().waitFor();checks.push(`${lang}: load error and retry recovery`);
mode='loading';await p.goto(base+'/terms',{waitUntil:'domcontentloaded'});await p.locator('.workspace-skeleton[aria-busy="true"]').waitFor();await p.waitForFunction(()=>document.readyState==='complete');while(!release)await p.waitForTimeout(50);await p.screenshot({path:`${out}/${lang}-loading.png`});mode='normal';release();await p.locator('.terms-card').first().waitFor();checks.push(`${lang}: loading state recovers`);await p.unroute('**/api/bootstrap');
await p.goto(base+'/terms',{waitUntil:'networkidle'});await p.locator('.learner-menu-toggle').click();for(let i=0;i<24;i++){await p.keyboard.press('Tab');assert.ok(await p.evaluate(()=>!!document.activeElement.closest('.terms-reference-sidebar')));}await p.keyboard.press('Escape');assert.equal(await p.locator('.learner-menu-toggle').getAttribute('aria-expanded'),'false');checks.push(`${lang}: learner drawer keyboard containment and Escape`);await c.close();console.log(checks.slice(-6));
// Verify a separate signed-out return-path flow.
const r=await b.newContext({reducedMotion:'reduce'}),rp=await r.newPage();await rp.goto(base+'/login?next=%2Fterms%3Fcategory%3DContracts',{waitUntil:'networkidle'});await rp.locator('input[type=email]').fill('maria@legalenglish5.test');await rp.locator('input[type=password]').fill('Maria#Alpha26');await rp.locator('.auth-reference-submit').click();await rp.waitForURL('**/terms?category=Contracts');checks.push('Auth return path retains category filter');await r.close();}
const c=await b.newContext({viewport:{width:1440,height:1000},reducedMotion:'no-preference'}),p=await c.newPage();await p.goto(base,{waitUntil:'networkidle'});const hero=p.locator('.hero-depth');await p.mouse.move(0,0);await p.waitForFunction(()=>document.querySelector('.hero-depth').dataset.motion==='running');await hero.hover();assert.equal(await hero.getAttribute('data-motion'),'paused');assert.equal(await p.locator('.hero-depth-card.front img').evaluate(e=>getComputedStyle(e).animationPlayState),'paused');await p.mouse.move(0,0);await p.locator('.hero-depth-dots button').first().focus();assert.equal(await hero.getAttribute('data-motion'),'paused');await p.keyboard.press('ArrowRight');await p.waitForTimeout(1000);assert.equal(await p.locator('.hero-depth-dots button').nth(1).getAttribute('aria-current'),'true');await p.evaluate(()=>document.activeElement.blur());await p.evaluate(()=>scrollTo(0,document.body.scrollHeight));await p.waitForFunction(()=>document.querySelector('.hero-depth').dataset.motion==='paused');await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.locator('.hero-depth-card.front img').evaluate(e=>getComputedStyle(e).animationName),'none');checks.push('Motion: hover/focus pauses images and slides; arrows change slides; offscreen pause; live reduced-motion change');await c.close();assert.deepEqual(issues,[]);fs.writeFileSync(out+'/states.json',JSON.stringify({checks,issues},null,2));console.log('All state/auth/motion checks passed.');}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
