import type { Locale } from "@/lib/i18n";

/** Owner console copy. Kept separate from lib/i18n.ts because it is Owner-only. */
const en = {
  ownerOnlyTitle: "Owner access required",
  ownerOnlyBody: "This route is rejected for Learners on the server, not only hidden in the menu.",
  termSaved: "Term saved.",
  couldNotSave: "Could not save.",
  saveBeforeAudio: "Save the term once, so it has a TermID, before uploading audio.",
  audioUploaded: "Audio{jur} uploaded.",
  audioUploadFailed: "Audio upload failed.",
  audioRemoved: "Audio{jur} removed. The publication gate applies again.",
  audioRemoveFailed: "Could not remove audio.",
  batchDone: "Audio batch processed.",
  batchFailed: "Audio batch failed.",
  eyebrow: "OWNER CONSOLE · NO CODE",
  title: "Operate the studio",
  lead: "LC-001 from MCD v1.3.81 loads unpublished. Publish only with quiz + AudioUS (and AudioUK for EMP-009). Import does not rewrite the MCD.",
  newTerm: "+ New term",
  tabOverview: "Overview",
  tabTerms: "Terms",
  tabUsers: "Users",
  tabImport: "Excel import",
  statLoaded: "MCD terms loaded",
  statPublished: "Published",
  statDrafts: "Drafts / future",
  statQuizzes: "Quizzes on Approved terms",
  learnersSee: "Learners currently see {n} terms. Approved is not Published. AudioUS is 0/30 in v1.3.81, so publication stays blocked until you upload audio.",
  usersGrowth: "Users growth",
  usersGrowthBody: "Alpha account activity by review session.",
  insightsVisits: "Visits",
  insightsVisitsBody: "Anonymous first-party count: no cookies, no third-party script. Automated browsers are excluded.",
  insightsRange: "Period",
  insightsDays: "{n} d",
  insightsVisitsLabel: "Visits",
  insightsViewsLabel: "Page views",
  insightsMobileLabel: "On phones",
  insightsSpanishLabel: "In Spanish",
  insightsChartAlt: "{n} page views over the last {days} days",
  insightsEmpty: "No visits recorded yet. Numbers appear as soon as someone opens the site.",
  insightsError: "Insights could not be loaded.",
  insightsLoading: "Loading…",
  insightsVitals: "Speed as visitors feel it",
  insightsVitalsBody: "75th percentile of Google's Core Web Vitals measured in real browsers.",
  insightsTopPages: "Most viewed pages",
  insightsTopPagesBody: "Where visitors actually spend their time.",
  vitalLCP: "Largest content painted",
  vitalCLS: "Layout stability",
  vitalINP: "Response to taps and clicks",
  vitalTTFB: "Server response",
  vitalGood: "Good",
  vitalNeedsWork: "Needs work",
  vitalPoor: "Poor",
  vitalNoData: "No data yet",
  topCategories: "Top categories",
  topCategoriesBody: "Published catalogue mix.",
  recentActivity: "Recent activity",
  recentActivityBody: "Operational signals for the owner.",
  newUser: "New user registered",
  awaitingAudio: "Terms awaiting audio",
  publishedTerms: "Published terms",
  roleOwner: "Owner",
  roleLearner: "Learner",
  verified: "verified",
  unverified: "unverified",
  grantAccess: "Grant 30-day access",
  importTitle: "Mass import from the Master Content Database",
  importBody: "Use MCD v1.3.81. The importer reads LC-001 only, keeps canonical IDs, accepts 3- or 4-option quizzes, and never publishes or deletes automatically.",
  previewReady: "Preview ready. Review the rows, then confirm. Nothing is published on import.",
  fileBlocking: "The file has blocking errors.",
  versionNa: "version n/a",
  previewSummary: "{version} · {terms} LC-001 terms · {creates} new · {updates} updates · {unchanged} unchanged · {quizzes} quizzes ({three}×3 / {four}×4)",
  row: "row",
  confirmImport: "Confirm import",
  importCommitted: "Import committed. Terms stay unpublished. Missing IDs were kept.",
  importFailed: "Import failed.",
  lastCommit: "Last commit: {inserted} inserted · {updated} updated",
  missingKept: " · {n} existing TermID(s) kept, not touched",
  rolledBack: " · rolled back",
  rollbackDone: "Import rolled back to its pre-commit state.",
  rollbackFailed: "Rollback failed.",
  undoImport: "Undo this import",
  bulkAudioTitle: "Bulk audio upload",
  bulkAudioBody1: "Name each file",
  bulkAudioBody2: "or",
  bulkAudioBody3: "(also m4a, wav, ogg) — for example",
  bulkAudioBody4:
    "Files are associated by name; anything that does not match an existing TermID is rejected and listed below, never guessed. Uploading the same name again replaces the previous recording.",
  audioCount: "AudioUS: {us}/{total} · AudioUK (EMP-009): {uk}",
  present: "present",
  pending: "pending",
  quizOpts: "Quiz {n} opts",
  quizMissing: "Quiz missing",
  noAudioUs: "No AudioUS",
  publishBlocked: "Publish blocked.",
  filterSearch: "Search by term, ID, Spanish equivalent or topic",
  filterStatus: "Filter by status",
  filterAll: "Active",
  filterReady: "Ready to publish",
  filterBlocked: "Blocked",
  filterArchived: "Archived",
  filterCategory: "Category",
  filterAllCategories: "All categories",
  filterEmpty: "No terms match these filters.",
  published: "Published",
  draft: "Draft",
  edit: "Edit",
  restore: "Restore",
  archive: "Archive",
  deleteConfirm: "Permanently delete {id}? This cannot be undone.",
  deleteFailed: "Delete failed.",
  deleted: "{id} deleted.",
  delete: "Delete",
  backupTitle: "Backup & recovery",
  backupBody:
    "Export downloads terms, quizzes, users, subscriptions and progress as JSON — everything except audio files, which live in Storage and are covered by the daily database backup instead. Nothing is deleted or changed by exporting.",
  exportJson: "Export data (JSON)",
  backupNote:
    "What's recovered and by whom: this export restores content/users/progress into a new environment by hand. Point-in-time database recovery (up to 24h RPO) is a Supabase Pro feature, requested from Supabase support, not from this panel — it does not restore Vercel, Mercado Pago or DNS configuration.",
  resetAlpha: "Reset alpha data",
  editTerm: "Edit {term}",
  newTermTitle: "New term",
  fTermId: "TermID",
  fTerm: "Term",
  fSpanish: "Spanish equivalent",
  fCivil: "Civil Law Equivalent",
  fCategory: "Category",
  fJurisdiction: "Jurisdiction",
  fDefinition: "Definition",
  fAlert: "Spanish Speaker Alert",
  fAudioUs: "AudioUS path",
  fAudioUsPh: "Required to publish",
  removeAudioUs: "Remove AudioUS",
  fAudioUk: "AudioUK path",
  fAudioUkReq: "Required for EMP-009",
  fAudioUkOpt: "Optional unless applicable",
  removeAudioUk: "Remove AudioUK",
  fUseItWith: "Use It With",
  fInContext: "In Context",
  fQuizQuestion: "Quiz question",
  fOption: "Option {letter}",
  optional: " (optional)",
  fQuizExplanation: "Quiz explanation",
  publishedCheck: "Published (blocked without quiz + AudioUS)",
  cancel: "Cancel",
  saveTerm: "Save term",
};

const es: typeof en = {
  ownerOnlyTitle: "Se requiere acceso de Titular",
  ownerOnlyBody: "El servidor rechaza esta ruta para los alumnos; no está solo oculta en el menú.",
  termSaved: "Término guardado.",
  couldNotSave: "No se pudo guardar.",
  saveBeforeAudio: "Guarda el término una vez, para que tenga TermID, antes de subir audio.",
  audioUploaded: "Audio{jur} subido.",
  audioUploadFailed: "Falló la subida del audio.",
  audioRemoved: "Audio{jur} retirado. La compuerta de publicación vuelve a aplicarse.",
  audioRemoveFailed: "No se pudo retirar el audio.",
  batchDone: "Lote de audio procesado.",
  batchFailed: "Falló el lote de audio.",
  eyebrow: "CONSOLA DE LA TITULAR · SIN CÓDIGO",
  title: "Opera el estudio",
  lead: "LC-001 del MCD v1.3.81 se carga sin publicar. Publica solo con quiz + AudioUS (y AudioUK para EMP-009). La importación no reescribe el MCD.",
  newTerm: "+ Nuevo término",
  tabOverview: "Resumen",
  tabTerms: "Términos",
  tabUsers: "Usuarios",
  tabImport: "Importar Excel",
  statLoaded: "Términos del MCD cargados",
  statPublished: "Publicados",
  statDrafts: "Borradores / futuros",
  statQuizzes: "Quizzes en términos Approved",
  learnersSee: "Los alumnos ven ahora {n} términos. Approved no es Published. AudioUS está en 0/30 en v1.3.81, así que la publicación sigue bloqueada hasta que subas el audio.",
  usersGrowth: "Crecimiento de usuarios",
  usersGrowthBody: "Actividad de cuentas alpha por sesión de revisión.",
  insightsVisits: "Visitas",
  insightsVisitsBody: "Conteo anónimo propio: sin cookies ni scripts de terceros. Los navegadores automatizados se excluyen.",
  insightsRange: "Periodo",
  insightsDays: "{n} d",
  insightsVisitsLabel: "Visitas",
  insightsViewsLabel: "Páginas vistas",
  insightsMobileLabel: "Desde móvil",
  insightsSpanishLabel: "En español",
  insightsChartAlt: "{n} páginas vistas en los últimos {days} días",
  insightsEmpty: "Aún no hay visitas registradas. Los números aparecen en cuanto alguien abre el sitio.",
  insightsError: "No se pudieron cargar las métricas.",
  insightsLoading: "Cargando…",
  insightsVitals: "Velocidad tal como la sienten los visitantes",
  insightsVitalsBody: "Percentil 75 de los Core Web Vitals de Google medidos en navegadores reales.",
  insightsTopPages: "Páginas más vistas",
  insightsTopPagesBody: "Dónde pasan realmente el tiempo los visitantes.",
  vitalLCP: "Contenido principal pintado",
  vitalCLS: "Estabilidad del diseño",
  vitalINP: "Respuesta a toques y clics",
  vitalTTFB: "Respuesta del servidor",
  vitalGood: "Bien",
  vitalNeedsWork: "Mejorable",
  vitalPoor: "Deficiente",
  vitalNoData: "Sin datos aún",
  topCategories: "Categorías principales",
  topCategoriesBody: "Mezcla del catálogo publicado.",
  recentActivity: "Actividad reciente",
  recentActivityBody: "Señales operativas para la titular.",
  newUser: "Nuevo usuario registrado",
  awaitingAudio: "Términos a la espera de audio",
  publishedTerms: "Términos publicados",
  roleOwner: "Titular",
  roleLearner: "Alumno",
  verified: "verificado",
  unverified: "sin verificar",
  grantAccess: "Conceder 30 días de acceso",
  importTitle: "Importación masiva desde la Master Content Database",
  importBody: "Usa el MCD v1.3.81. El importador lee solo LC-001, conserva los IDs canónicos, acepta quizzes de 3 o 4 opciones y nunca publica ni borra automáticamente.",
  previewReady: "Vista previa lista. Revisa las filas y confirma. Nada se publica al importar.",
  fileBlocking: "El archivo tiene errores bloqueantes.",
  versionNa: "versión n/d",
  previewSummary: "{version} · {terms} términos LC-001 · {creates} nuevos · {updates} actualizados · {unchanged} sin cambios · {quizzes} quizzes ({three}×3 / {four}×4)",
  row: "fila",
  confirmImport: "Confirmar importación",
  importCommitted: "Importación confirmada. Los términos siguen sin publicar. Los IDs ausentes se conservaron.",
  importFailed: "Falló la importación.",
  lastCommit: "Último commit: {inserted} insertados · {updated} actualizados",
  missingKept: " · {n} TermID existentes conservados, sin tocar",
  rolledBack: " · revertido",
  rollbackDone: "Importación revertida a su estado previo.",
  rollbackFailed: "Falló la reversión.",
  undoImport: "Deshacer esta importación",
  bulkAudioTitle: "Carga masiva de audio",
  bulkAudioBody1: "Nombra cada archivo",
  bulkAudioBody2: "o",
  bulkAudioBody3: "(también m4a, wav, ogg); por ejemplo",
  bulkAudioBody4:
    "Los archivos se asocian por nombre; todo lo que no coincida con un TermID existente se rechaza y se lista abajo, nunca se adivina. Subir el mismo nombre otra vez reemplaza la grabación anterior.",
  audioCount: "AudioUS: {us}/{total} · AudioUK (EMP-009): {uk}",
  present: "presente",
  pending: "pendiente",
  quizOpts: "Quiz de {n} opciones",
  quizMissing: "Sin quiz",
  noAudioUs: "Sin AudioUS",
  publishBlocked: "Publicación bloqueada.",
  filterSearch: "Buscar por término, ID, equivalente en español o tema",
  filterStatus: "Filtrar por estado",
  filterAll: "Activos",
  filterReady: "Listos para publicar",
  filterBlocked: "Bloqueados",
  filterArchived: "Archivados",
  filterCategory: "Categoría",
  filterAllCategories: "Todas las categorías",
  filterEmpty: "Ningún término coincide con estos filtros.",
  published: "Publicado",
  draft: "Borrador",
  edit: "Editar",
  restore: "Restaurar",
  archive: "Archivar",
  deleteConfirm: "¿Eliminar {id} de forma permanente? No se puede deshacer.",
  deleteFailed: "Falló la eliminación.",
  deleted: "{id} eliminado.",
  delete: "Eliminar",
  backupTitle: "Respaldo y recuperación",
  backupBody:
    "La exportación descarga términos, quizzes, usuarios, suscripciones y progreso en JSON: todo salvo los archivos de audio, que viven en Storage y quedan cubiertos por el respaldo diario de la base de datos. Exportar no borra ni cambia nada.",
  exportJson: "Exportar datos (JSON)",
  backupNote:
    "Qué se recupera y quién lo hace: esta exportación permite restaurar contenido/usuarios/progreso en un ambiente nuevo de forma manual. La recuperación punto en el tiempo de la base de datos (RPO de hasta 24 h) es una función de Supabase Pro que se solicita al soporte de Supabase, no desde este panel; no restaura la configuración de Vercel, Mercado Pago ni DNS.",
  resetAlpha: "Restablecer datos alpha",
  editTerm: "Editar {term}",
  newTermTitle: "Nuevo término",
  fTermId: "TermID",
  fTerm: "Término",
  fSpanish: "Equivalente en español",
  fCivil: "Equivalente en derecho civil",
  fCategory: "Categoría",
  fJurisdiction: "Jurisdicción",
  fDefinition: "Definición",
  fAlert: "Alerta para hispanohablantes",
  fAudioUs: "Ruta AudioUS",
  fAudioUsPh: "Obligatorio para publicar",
  removeAudioUs: "Retirar AudioUS",
  fAudioUk: "Ruta AudioUK",
  fAudioUkReq: "Obligatorio para EMP-009",
  fAudioUkOpt: "Opcional salvo que aplique",
  removeAudioUk: "Retirar AudioUK",
  fUseItWith: "Se usa con",
  fInContext: "En contexto",
  fQuizQuestion: "Pregunta del quiz",
  fOption: "Opción {letter}",
  optional: " (opcional)",
  fQuizExplanation: "Explicación del quiz",
  publishedCheck: "Publicado (bloqueado sin quiz + AudioUS)",
  cancel: "Cancelar",
  saveTerm: "Guardar término",
};

export type AdminKey = keyof typeof en;
const copy: Record<Locale, typeof en> = { en, es };

export function adminText(locale: Locale, key: AdminKey, vars?: Record<string, string | number>) {
  let text = copy[locale][key];
  if (vars) for (const [name, value] of Object.entries(vars)) text = text.replaceAll(`{${name}}`, String(value));
  return text;
}
