export type Role = "student" | "admin";
export type SubscriptionStatus = "trialing" | "active" | "payment_failed" | "cancelled" | "expired" | "exceptional_access";
export type Quiz = { question:string; options:[string,string,string]; correctIndex:number; feedback:string };
export type Term = { id:string; term:string; pronunciation:string; jurisdiction:"US"|"UK"|"US/UK"; plainDefinition:string; spanishEquivalent:string; spanishAlert:string; useItWith:string[]; example:string; quiz:Quiz|null; published:boolean; archived:boolean; createdAt:string; updatedAt:string };
export type Progress = { userId:string; termId:string; favourite:boolean; quizCompleted:boolean; attempts:number; updatedAt:string };
export type Subscription = { status:SubscriptionStatus; trialStartedAt:string; trialEndsAt:string; accessUntil:string|null; provider:"simulator"; providerReference:string|null };
export type User = { id:string; name:string; email:string; password:string; role:Role; subscription:Subscription };
export type Session = { user:User; subscription:Subscription };

const now = () => new Date().toISOString();
const plusDays = (date:Date,days:number) => new Date(date.getTime()+days*86400000).toISOString();
export function trialSubscription(date=new Date()):Subscription{return {status:"trialing",trialStartedAt:date.toISOString(),trialEndsAt:plusDays(date,7),accessUntil:null,provider:"simulator",providerReference:null}}
export function entitlementFor(subscription:Subscription, date=new Date()){
 const trialValid=subscription.status==="trialing"&&new Date(subscription.trialEndsAt)>date;
 const paid=subscription.status==="active";
 const exception=subscription.status==="exceptional_access"&&!!subscription.accessUntil&&new Date(subscription.accessUntil)>date;
 if(trialValid) return {allowed:true,label:"Trial active",detail:`Trial ends ${new Date(subscription.trialEndsAt).toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"})}.`};
 if(paid) return {allowed:true,label:"Subscription active",detail:"Your simulated monthly subscription is active."};
 if(exception) return {allowed:true,label:"Exceptional access",detail:`Access granted until ${new Date(subscription.accessUntil!).toLocaleDateString("en-US")}.`};
 const labels:Record<string,string>={payment_failed:"Payment failed",cancelled:"Subscription cancelled",expired:"Trial expired"};
 return {allowed:false,label:labels[subscription.status]||"Access blocked",detail:"Protected learning content is unavailable until access is restored."};
}
export function emptyTerm():Term{return {id:"",term:"",pronunciation:"",jurisdiction:"US",plainDefinition:"",spanishEquivalent:"",spanishAlert:"",useItWith:[],example:"",quiz:null,published:false,archived:false,createdAt:now(),updatedAt:now()}}
export function userCanReadProgress(actor:User,record:Progress){return actor.role==="admin"||actor.id===record.userId}
export function userCanManageTerms(actor:User){return actor.role==="admin"}

export const seedTerms:Term[]=[
 {id:"consideration",term:"Consideration",pronunciation:"/kənˌsɪdəˈreɪʃən/",jurisdiction:"US",plainDefinition:"Something of legal value exchanged between the parties to support an enforceable contract.",spanishEquivalent:"Contraprestación",spanishAlert:"It does not mean thoughtful attention. In U.S. contract law, it refers to the bargained-for legal value exchanged by the parties.",useItWith:["adequate consideration","for good and valuable consideration","lack of consideration"],example:"The parties acknowledged that the mutual promises constituted sufficient consideration for the agreement.",quiz:{question:"In U.S. contract law, what is consideration?",options:["A careful review of documents","Something of legal value exchanged by the parties","A court's interpretation of a clause"],correctIndex:1,feedback:"Consideration is the bargained-for legal value exchanged to support an enforceable contract."},published:true,archived:false,createdAt:now(),updatedAt:now()},
 {id:"assignment",term:"Assignment",pronunciation:"/əˈsaɪnmənt/",jurisdiction:"US/UK",plainDefinition:"A transfer of a contractual right from one person or entity to another.",spanishEquivalent:"Cesión",spanishAlert:"In contracts, assignment usually means cesión—not a school task or work assignment.",useItWith:["assignment of rights","prohibit assignment","consent to assignment"],example:"The agreement prohibits assignment of the tenant's rights without the landlord's prior written consent.",quiz:{question:"What does assignment usually transfer?",options:["A contractual right","A court judgment","A statutory definition"],correctIndex:0,feedback:"An assignment commonly transfers a contractual right from the assignor to the assignee."},published:true,archived:false,createdAt:now(),updatedAt:now()},
 {id:"construction",term:"Construction",pronunciation:"/kənˈstrʌkʃən/",jurisdiction:"US/UK",plainDefinition:"The process of determining or explaining the legal meaning of a statute, contract or other legal text.",spanishEquivalent:"Interpretación",spanishAlert:"In legal context, construction may mean interpretación—not the construction of a building.",useItWith:["narrow construction","statutory construction","rules of construction"],example:"The court adopted a narrow construction of the limitation-of-liability clause.",quiz:{question:"Which phrase concerns legal interpretation?",options:["Construction site","Narrow construction of a clause","Construction materials"],correctIndex:1,feedback:"A narrow construction limits the interpreted scope of the legal text."},published:true,archived:false,createdAt:now(),updatedAt:now()},
 {id:"force-majeure",term:"Force Majeure",pronunciation:"/ˌfɔːrs mæˈʒɜːr/",jurisdiction:"US/UK",plainDefinition:"An extraordinary event beyond a party's reasonable control that may excuse or suspend contractual performance when the clause applies.",spanishEquivalent:"Fuerza mayor",spanishAlert:"The effect depends on the wording of the contract and the governing law; the label alone does not automatically excuse performance.",useItWith:["force majeure event","invoke force majeure","force majeure clause"],example:"The supplier invoked the force majeure clause after the port was closed by government order.",quiz:{question:"What primarily determines the effect of force majeure?",options:["The contract wording and governing law","The event's publicity","The breaching party's preference"],correctIndex:0,feedback:"The clause and governing law determine whether performance is excused, suspended or unaffected."},published:true,archived:false,createdAt:now(),updatedAt:now()},
 {id:"breach",term:"Breach",pronunciation:"/briːtʃ/",jurisdiction:"US/UK",plainDefinition:"A failure to perform a contractual duty or comply with another legal obligation.",spanishEquivalent:"Incumplimiento",spanishAlert:"Use breach as a noun in breach of contract and as a regular transitive verb: a party breaches the contract.",useItWith:["material breach","breach the agreement","remedy a breach"],example:"Failure to deliver the goods by the agreed date may constitute a material breach.",quiz:{question:"Which sentence uses breach correctly as a verb?",options:["The seller breached the agreement.","The seller breached of the agreement.","The seller made a breach the agreement."],correctIndex:0,feedback:"Breach is a regular transitive verb: breach the agreement; breached the agreement."},published:true,archived:false,createdAt:now(),updatedAt:now()}
];

export const seedUsers:User[]=[
 {id:"student-demo",name:"Alex Student",email:"student@demo.test",password:"demo1234",role:"student",subscription:trialSubscription(new Date())},
 {id:"student-second",name:"Marta Student",email:"marta@demo.test",password:"demo1234",role:"student",subscription:trialSubscription(new Date())},
 {id:"admin-demo",name:"MPC Owner",email:"admin@demo.test",password:"admin1234",role:"admin",subscription:{...trialSubscription(new Date()),status:"exceptional_access",accessUntil:plusDays(new Date(),3650)}}
];
