import type { Locale } from "@/lib/i18n";

/** Copy for the learner workspace (shell, library, term detail, quizzes, progress, account, categories, my library). */
const en = {
  // shell
  navHome: "Home",
  navLibrary: "Terms Library",
  navCategories: "Categories",
  navProgress: "Progress",
  navQuizzes: "Quizzes",
  navMyLibrary: "My Library",
  navAccount: "Account",
  navBilling: "Billing",
  navHelp: "Help & Support",
  navSettings: "Settings",
  navAdmin: "Admin panel",
  signOut: "Sign Out",
  searchPlaceholder: "Search terms, categories, or content...",
  notifications: "Notifications",
  upgradeNow: "Upgrade Now",
  manageAccess: "Manage access",
  owner: "Owner",
  learner: "Learner",
  opening: "Opening your studio…",
  accessPaused: "Access paused",
  accessInactive: "Your trial or subscription is not active.",
  accessRefresh: "This decision is stored on the server. Refreshing the browser will not restore access.",
  reviewAccess: "Review Mercado Pago access",
  deactivatedTitle: "This account is deactivated.",
  deactivatedBody: "You paused this account yourself from Account. Nothing was deleted — your content and progress are exactly as you left them.",
  reactivate: "Reactivate account",
  // library
  libraryTitle: "Terms Library",
  libraryLead: "Explore and master essential legal terminology.",
  libraryLeadOwner: "You see every MCD term, including drafts. Learners only see Published terms.",
  allTerms: "All Terms",
  stateNew: "New",
  stateLearning: "Learning",
  stateMastered: "Mastered",
  allCategories: "All Categories",
  termsCount: "{n} Terms",
  termsCountOne: "1 Term",
  draft: "Draft",
  saved: "Saved",
  save: "Save",
  emptyLibraryTitle: "Nothing published yet",
  emptyLibraryBody: "Terms appear here as soon as the Owner publishes them (quiz + AudioUS required). Approved is not Published.",
  emptySearch: "No terms match your search.",
  showing: "Showing {from}–{to} of {n}",
  perPage: "per page",
  previous: "Previous",
  next: "Next",
  // detail
  breadcrumbLibrary: "Terms Library",
  pronunciation: "Pronunciation",
  playUs: "Play US pronunciation",
  playUk: "Play UK pronunciation",
  audioPending: "Audio pending",
  learningStatus: "Learning Status",
  definition: "Definition",
  spanishEquivalent: "Spanish Equivalent",
  commonTranslation: "Common Translation",
  civilLaw: "Civil Law Equivalent",
  legalSystemNote: "Legal System Note",
  speakerAlert: "Spanish-Speaker Alert",
  useItWith: "Use It With",
  inContext: "In Context",
  realWorld: "Real-World Example",
  usVariant: "US usage",
  ukVariant: "UK usage",
  takeQuizToMaster: "Take the quiz",
  masteredDone: "Mastered",
  addToLibrary: "Add to My Library",
  inMyLibrary: "In My Library",
  nextTerm: "Next Term: {term}",
  previousTerm: "Previous Term",
  nextTermShort: "Next Term",
  quickQuiz: "Quick Quiz",
  oneOfOne: "1 of 1",
  checkAnswer: "Check Answer",
  tryAgain: "Try again",
  correct: "Correct!",
  incorrect: "Not quite.",
  noQuiz: "This term has no quiz yet, so it cannot be published or mastered.",
  yourProgress: "Your Progress",
  understanding: "Understanding",
  progressNew: "You have not studied this term yet. Reading it moves it to Learning.",
  progressLearning: "You've marked this term as Learning. Answer the quiz correctly to master it.",
  progressMastered: "You mastered this term. Attempts: {n}.",
  relatedTerms: "Related Terms",
  viewAllIn: "View all in {category}",
  source: "Source of truth",
  sourceMcd: "MCD workbook",
  sourceEditorial: "Editorial version",
  sourceReviewed: "Last reviewed",
  sourceStatus: "MCD status",
  attempts: "Attempts",
  termNotFound: "This term is not available.",
  termNotFoundBody: "It may be unpublished or the link is wrong.",
  backToLibrary: "Back to Terms Library",
  // quizzes
  quizTitle: "Quiz & Progress",
  quizLead: "Test your knowledge and track your mastery over legal terms.",
  quizAccuracy: "Quiz Accuracy",
  quizzesCompleted: "Quizzes Completed",
  currentStreak: "Current Streak",
  termsMastered: "Terms Mastered",
  days: "Days",
  day: "Day",
  best: "Best: {n} days",
  ofQuizzed: "quizzed terms",
  totalAttempts: "attempts",
  activeQuiz: "Active Quiz",
  questionOf: "Question {i} of {n}",
  quizFor: "{category} Quiz",
  allQuiz: "Mixed Quiz",
  endQuiz: "End Quiz",
  nextQuestion: "Next Question",
  finish: "Finish",
  sessionDone: "Session complete",
  sessionSummary: "{correct} of {n} correct. Mastered terms stay mastered; the others remain in Learning.",
  startAgain: "Start again",
  noQuizzes: "No quizzes available yet. Quizzes appear with published terms.",
  recentHistory: "Recent Quiz History",
  viewAll: "View All",
  quiz: "Quiz",
  score: "Attempts",
  date: "Date",
  category: "Category",
  status: "Status",
  passed: "Passed",
  review: "Review",
  noHistory: "No quiz attempts yet.",
  recommended: "Recommended Practice",
  recommendedLead: "Focus on areas to improve your mastery.",
  needsPractice: "Needs Practice",
  goodProgress: "Good Progress",
  complete: "Complete",
  mastery: "Mastery: {pct}%",
  practiceNow: "Practice Now",
  overallMastery: "Overall Mastery",
  masteryWord: "Mastery",
  keepGoing: "Great progress! Keep practicing to strengthen your understanding.",
  startHint: "Open a term and pass its quiz to start building mastery.",
  masterySnapshot: "Mastery Snapshot",
  recentAchievements: "Recent Achievements",
  categoryAccuracy: "Category Mastery",
  fullReport: "View Full Report",
  // progress
  progressTitle: "My Progress",
  progressLead: "Track your learning journey and see how you're improving.",
  termsStudied: "Terms Studied",
  favourites: "Saved Terms",
  ofTotal: "of {n} available",
  learningActivity: "Learning Activity",
  lastWeeks: "Last 6 weeks",
  legendTerms: "Terms Studied",
  legendQuizzes: "Quiz Attempts",
  byCategory: "Progress by Category",
  viewCategories: "View all categories",
  streakGood: "Great job! Keep it up!",
  photoCardTag: "Study anywhere",
  photoCardTitle: "Five minutes between hearings is enough for one term",
  quizPhotoTag: "Before you test",
  quizPhotoTitle: "Reread the term card, then answer without looking",
  detailPhotoTag: "Keep going",
  detailPhotoTitle: "Take a mixed quiz on everything you have opened",
  categoriesHeroTag: "MCD v1.3.81 · Three canonical categories",
  categoriesHeroTitle: "Every term belongs to exactly one category, as approved in the Master Content Database",
  adminBannerTag: "Owner console",
  adminBannerTitle: "Import, review and publish, in that order",
  streakStart: "Study today to start a streak.",
  longest: "Longest streak: {n} days",
  recentActivity: "Recent Activity",
  noActivity: "No activity yet. Open a term to begin.",
  achievements: "Achievements",
  achieved: "Completed",
  today: "Today",
  yesterday: "Yesterday",
  mastered: "Mastered \u201c{term}\u201d",
  attempted: "Quiz attempt: {term}",
  studied: "Studied \u201c{term}\u201d",
  savedTerm: "Saved \u201c{term}\u201d",
  achFirstSteps: "First Steps",
  achFirstStepsBody: "Study 10 terms",
  achQuizMaster: "Quiz Master",
  achQuizMasterBody: "Complete 10 quizzes",
  achConsistent: "Consistent Learner",
  achConsistentBody: "Maintain a 7-day streak",
  achFirstMastery: "First Mastery",
  achFirstMasteryBody: "Master your first term",
  achChampion: "Category Champion",
  achChampionBody: "Master every term in a category",
  // account
  accountTitle: "Account",
  accountLead: "Manage your profile, preferences, and account settings.",
  tabProfile: "Profile",
  tabPreferences: "Preferences",
  tabSecurity: "Security",
  tabNotifications: "Notifications",
  profileInfo: "Profile Information",
  editProfile: "Edit Profile",
  saveProfile: "Save",
  cancel: "Cancel",
  fullName: "Full Name",
  email: "Email Address",
  role: "Role",
  memberSince: "Member since",
  emailStatus: "Email status",
  verified: "Verified",
  unverified: "Not verified",
  language: "Interface language",
  joined: "Joined {date}",
  accountSettings: "Account Settings",
  changePassword: "Change Password",
  changePasswordBody: "Update your password to keep your account secure.",
  currentPassword: "Current password",
  newPassword: "New password (8+ characters)",
  passwordChanged: "Password updated.",
  deactivate: "Deactivate Account",
  deactivateBody: "Pause your account without deleting anything. Reactivate any time by logging in.",
  deactivateAction: "Deactivate",
  deleteAccount: "Delete Account",
  deleteBody: "Permanently delete your account and all data.",
  deleteAction: "Delete",
  deleteConfirm: "Delete your account and all progress permanently? This cannot be undone.",
  profileSaved: "Profile updated.",
  avgAttempts: "Attempts per term",
  viewFullProgress: "View Full Progress",
  subscription: "Subscription",
  plan: "Plan",
  planTrial: "7-day trial",
  planMonthly: "Monthly plan",
  planAnnual: "Annual plan",
  planNone: "No plan yet",
  trialEnds: "Trial ends",
  accessUntil: "Access until",
  periodEnd: "Current period ends",
  manageSubscription: "Manage Subscription",
  // categories / my library
  categoriesTitle: "Categories",
  categoriesLead: "The three canonical categories of the MCD. Pick one to filter the library.",
  browse: "Browse terms",
  myLibraryTitle: "My Library",
  myLibraryLead: "Terms you saved with the bookmark.",
  emptyMyLibrary: "Nothing saved yet. Use the bookmark on any term to keep it here.",
};

const es: typeof en = {
  navHome: "Inicio",
  navLibrary: "Biblioteca de términos",
  navCategories: "Categorías",
  navProgress: "Progreso",
  navQuizzes: "Quizzes",
  navMyLibrary: "Mi biblioteca",
  navAccount: "Cuenta",
  navBilling: "Facturación",
  navHelp: "Ayuda y soporte",
  navSettings: "Ajustes",
  navAdmin: "Consola",
  signOut: "Cerrar sesión",
  searchPlaceholder: "Buscar términos, categorías o contenido...",
  notifications: "Notificaciones",
  upgradeNow: "Mejorar plan",
  manageAccess: "Gestionar acceso",
  owner: "Titular",
  learner: "Alumno",
  opening: "Abriendo el estudio…",
  accessPaused: "Acceso en pausa",
  accessInactive: "Tu prueba o suscripción no está activa.",
  accessRefresh: "Esta decisión está en el servidor. Recargar el navegador no restablece el acceso.",
  reviewAccess: "Revisar acceso de Mercado Pago",
  deactivatedTitle: "Esta cuenta está desactivada.",
  deactivatedBody: "Pausaste esta cuenta desde Cuenta. No se borró nada: tu contenido y progreso están tal como los dejaste.",
  reactivate: "Reactivar cuenta",
  libraryTitle: "Biblioteca de términos",
  libraryLead: "Explora y domina la terminología jurídica esencial.",
  libraryLeadOwner: "Ves todos los términos del MCD, incluidos borradores. Los alumnos solo ven los Publicados.",
  allTerms: "Todos",
  stateNew: "Nuevo",
  stateLearning: "Aprendiendo",
  stateMastered: "Dominado",
  allCategories: "Todas las categorías",
  termsCount: "{n} términos",
  termsCountOne: "1 término",
  draft: "Borrador",
  saved: "Guardado",
  save: "Guardar",
  emptyLibraryTitle: "Aún no hay términos publicados",
  emptyLibraryBody: "Los términos aparecen aquí cuando la titular los publica (requiere quiz + AudioUS). Approved no es Published.",
  emptySearch: "Ningún término coincide con tu búsqueda.",
  showing: "Mostrando {from}–{to} de {n}",
  perPage: "por página",
  previous: "Anterior",
  next: "Siguiente",
  breadcrumbLibrary: "Biblioteca de términos",
  pronunciation: "Pronunciación",
  playUs: "Reproducir pronunciación US",
  playUk: "Reproducir pronunciación UK",
  audioPending: "Audio pendiente",
  learningStatus: "Estado de aprendizaje",
  definition: "Definición",
  spanishEquivalent: "Equivalente en español",
  commonTranslation: "Traducción habitual",
  civilLaw: "Equivalente en derecho civil",
  legalSystemNote: "Nota de sistema jurídico",
  speakerAlert: "Alerta para hispanohablantes",
  useItWith: "Se usa con",
  inContext: "En contexto",
  realWorld: "Ejemplo real",
  usVariant: "Uso en EE. UU.",
  ukVariant: "Uso en Reino Unido",
  takeQuizToMaster: "Hacer el quiz",
  masteredDone: "Dominado",
  addToLibrary: "Guardar en Mi biblioteca",
  inMyLibrary: "En Mi biblioteca",
  nextTerm: "Siguiente: {term}",
  previousTerm: "Término anterior",
  nextTermShort: "Término siguiente",
  quickQuiz: "Quiz rápido",
  oneOfOne: "1 de 1",
  checkAnswer: "Comprobar respuesta",
  tryAgain: "Intentar de nuevo",
  correct: "¡Correcto!",
  incorrect: "No es correcto.",
  noQuiz: "Este término aún no tiene quiz, así que no puede publicarse ni dominarse.",
  yourProgress: "Tu progreso",
  understanding: "Comprensión",
  progressNew: "Aún no has estudiado este término. Leerlo lo pasa a Aprendiendo.",
  progressLearning: "Este término está en Aprendiendo. Responde bien el quiz para dominarlo.",
  progressMastered: "Dominaste este término. Intentos: {n}.",
  relatedTerms: "Términos relacionados",
  viewAllIn: "Ver todos en {category}",
  source: "Fuente de verdad",
  sourceMcd: "Libro MCD",
  sourceEditorial: "Versión editorial",
  sourceReviewed: "Última revisión",
  sourceStatus: "Estado MCD",
  attempts: "Intentos",
  termNotFound: "Este término no está disponible.",
  termNotFoundBody: "Puede que no esté publicado o que el enlace sea incorrecto.",
  backToLibrary: "Volver a la biblioteca",
  quizTitle: "Quiz y progreso",
  quizLead: "Pon a prueba tus conocimientos y sigue tu dominio de los términos.",
  quizAccuracy: "Precisión en quizzes",
  quizzesCompleted: "Quizzes completados",
  currentStreak: "Racha actual",
  termsMastered: "Términos dominados",
  days: "días",
  day: "día",
  best: "Mejor: {n} días",
  ofQuizzed: "términos evaluados",
  totalAttempts: "intentos",
  activeQuiz: "Quiz activo",
  questionOf: "Pregunta {i} de {n}",
  quizFor: "Quiz de {category}",
  allQuiz: "Quiz mixto",
  endQuiz: "Terminar",
  nextQuestion: "Siguiente pregunta",
  finish: "Finalizar",
  sessionDone: "Sesión completada",
  sessionSummary: "{correct} de {n} correctas. Los términos dominados se mantienen; el resto sigue en Aprendiendo.",
  startAgain: "Empezar de nuevo",
  noQuizzes: "Aún no hay quizzes. Aparecen con los términos publicados.",
  recentHistory: "Historial reciente",
  viewAll: "Ver todo",
  quiz: "Quiz",
  score: "Intentos",
  date: "Fecha",
  category: "Categoría",
  status: "Estado",
  passed: "Aprobado",
  review: "Repasar",
  noHistory: "Todavía no hay intentos.",
  recommended: "Práctica recomendada",
  recommendedLead: "Enfócate en las áreas que más lo necesitan.",
  needsPractice: "Necesita práctica",
  goodProgress: "Buen avance",
  complete: "Completa",
  mastery: "Dominio: {pct}%",
  practiceNow: "Practicar",
  overallMastery: "Dominio general",
  masteryWord: "Dominio",
  keepGoing: "¡Buen progreso! Sigue practicando para afianzar lo aprendido.",
  startHint: "Abre un término y aprueba su quiz para empezar a construir dominio.",
  masterySnapshot: "Resumen de dominio",
  recentAchievements: "Logros recientes",
  categoryAccuracy: "Dominio por categoría",
  fullReport: "Ver informe completo",
  progressTitle: "Mi progreso",
  progressLead: "Sigue tu camino de aprendizaje y mira cómo mejoras.",
  termsStudied: "Términos estudiados",
  favourites: "Términos guardados",
  ofTotal: "de {n} disponibles",
  learningActivity: "Actividad de aprendizaje",
  lastWeeks: "Últimas 6 semanas",
  legendTerms: "Términos estudiados",
  legendQuizzes: "Intentos de quiz",
  byCategory: "Progreso por categoría",
  viewCategories: "Ver todas las categorías",
  streakGood: "¡Muy bien! Sigue así.",
  photoCardTag: "Estudia donde estés",
  photoCardTitle: "Cinco minutos entre audiencias bastan para un término",
  quizPhotoTag: "Antes de evaluarte",
  quizPhotoTitle: "Relee la ficha del término y responde sin mirar",
  detailPhotoTag: "Sigue avanzando",
  detailPhotoTitle: "Haz un quiz mixto con todo lo que has abierto",
  categoriesHeroTag: "MCD v1.3.81 · Tres categorías canónicas",
  categoriesHeroTitle: "Cada término pertenece a una sola categoría, tal como se aprobó en el Master Content Database",
  adminBannerTag: "Consola de la propietaria",
  adminBannerTitle: "Importar, revisar y publicar, en ese orden",
  streakStart: "Estudia hoy para iniciar una racha.",
  longest: "Racha más larga: {n} días",
  recentActivity: "Actividad reciente",
  noActivity: "Sin actividad todavía. Abre un término para empezar.",
  achievements: "Logros",
  achieved: "Completado",
  today: "Hoy",
  yesterday: "Ayer",
  mastered: "Dominaste \u201c{term}\u201d",
  attempted: "Intento de quiz: {term}",
  studied: "Estudiaste \u201c{term}\u201d",
  savedTerm: "Guardaste \u201c{term}\u201d",
  achFirstSteps: "Primeros pasos",
  achFirstStepsBody: "Estudia 10 términos",
  achQuizMaster: "Maestro del quiz",
  achQuizMasterBody: "Completa 10 quizzes",
  achConsistent: "Constancia",
  achConsistentBody: "Mantén una racha de 7 días",
  achFirstMastery: "Primer dominio",
  achFirstMasteryBody: "Domina tu primer término",
  achChampion: "Campeón de categoría",
  achChampionBody: "Domina todos los términos de una categoría",
  accountTitle: "Cuenta",
  accountLead: "Gestiona tu perfil, preferencias y ajustes de la cuenta.",
  tabProfile: "Perfil",
  tabPreferences: "Preferencias",
  tabSecurity: "Seguridad",
  tabNotifications: "Notificaciones",
  profileInfo: "Información del perfil",
  editProfile: "Editar perfil",
  saveProfile: "Guardar",
  cancel: "Cancelar",
  fullName: "Nombre completo",
  email: "Correo electrónico",
  role: "Rol",
  memberSince: "Miembro desde",
  emailStatus: "Estado del correo",
  verified: "Verificado",
  unverified: "Sin verificar",
  language: "Idioma de la interfaz",
  joined: "Desde {date}",
  accountSettings: "Ajustes de la cuenta",
  changePassword: "Cambiar contraseña",
  changePasswordBody: "Actualiza tu contraseña para mantener la cuenta segura.",
  currentPassword: "Contraseña actual",
  newPassword: "Nueva contraseña (8+ caracteres)",
  passwordChanged: "Contraseña actualizada.",
  deactivate: "Desactivar cuenta",
  deactivateBody: "Pausa tu cuenta sin borrar nada. Reactívala cuando quieras al iniciar sesión.",
  deactivateAction: "Desactivar",
  deleteAccount: "Eliminar cuenta",
  deleteBody: "Elimina tu cuenta y todos tus datos de forma permanente.",
  deleteAction: "Eliminar",
  deleteConfirm: "¿Eliminar tu cuenta y todo tu progreso de forma permanente? No se puede deshacer.",
  profileSaved: "Perfil actualizado.",
  avgAttempts: "Intentos por término",
  viewFullProgress: "Ver progreso completo",
  subscription: "Suscripción",
  plan: "Plan",
  planTrial: "Prueba de 7 días",
  planMonthly: "Plan mensual",
  planAnnual: "Plan anual",
  planNone: "Sin plan aún",
  trialEnds: "La prueba termina",
  accessUntil: "Acceso hasta",
  periodEnd: "Fin del periodo actual",
  manageSubscription: "Gestionar suscripción",
  categoriesTitle: "Categorías",
  categoriesLead: "Las tres categorías canónicas del MCD. Elige una para filtrar la biblioteca.",
  browse: "Ver términos",
  myLibraryTitle: "Mi biblioteca",
  myLibraryLead: "Términos que guardaste con el marcador.",
  emptyMyLibrary: "Nada guardado todavía. Usa el marcador en cualquier término para tenerlo aquí.",
};

export type LearnerKey = keyof typeof en;
const copy: Record<Locale, typeof en> = { en, es };

export function learnerText(locale: Locale, key: LearnerKey, vars?: Record<string, string | number>) {
  let text = copy[locale][key];
  if (vars) for (const [name, value] of Object.entries(vars)) text = text.replaceAll(`{${name}}`, String(value));
  return text;
}
