import type { Locale } from "@/lib/i18n";

/** Copy for the learner workspace (shell, library, term detail, quizzes, progress, account, categories, my library). */
const en = {
  // shell
  navHome: "Home",
  brandHome: "Legal English 5 — go to the website home page",
  navLibrary: "Terms Library",
  navCategories: "Categories",
  navProgress: "Progress",
  navQuizzes: "Quizzes",
  navMyLibrary: "My Library",
  navAccount: "Account",
  navBilling: "Billing",
  navHelp: "Help & Support",
  navSettings: "Settings",
  navHowItWorks: "How It Works",
  navAdmin: "Admin panel",
  signOut: "Sign Out",
  searchPlaceholder: "Search terms, categories, or content...",
  notifications: "Notifications",
  upgradeNow: "Upgrade Now",
  manageAccess: "Manage access",
  owner: "Owner",
  learner: "Learner",
  opening: "Opening your studio…",
  loadFailed: "We could not reach the server. Check your connection and try again.",
  retry: "Try again",
  accessPaused: "Access paused",
  accessInactive: "Your trial or subscription is not active.",
  lockedCard: "Renew your access to read this term.",
  accessRefresh: "This decision is stored on the server. Refreshing the browser will not restore access.",
  reviewAccess: "Review Mercado Pago access",
  deactivatedTitle: "This account is deactivated.",
  deactivatedBody: "You paused this account yourself from Account. Nothing was deleted — your content and progress are exactly as you left them.",
  reactivate: "Reactivate account",
  // library
  libraryTitle: "Terms Library",
  libraryLead: "Explore and master essential legal terminology.",
  libraryLeadOwner: "You see every MCD term, including drafts. Learners only see Published terms.",
  allTerms: "All Terms",
  stateNew: "New",
  stateLearning: "Learning",
  stateMastered: "Mastered",
  allCategories: "All Categories",
  termsCount: "{n} Terms",
  termsCountOne: "1 Term",
  draft: "Draft",
  saved: "Saved",
  save: "Save",
  emptyLibraryTitle: "Nothing published yet",
  emptyLibraryBody: "Terms appear here as soon as the Owner publishes them (quiz + AudioUS required). Approved is not Published.",
  emptySearch: "No terms match your search.",
  showing: "Showing {from}–{to} of {n}",
  perPage: "per page",
  previous: "Previous",
  next: "Next",
  // detail
  breadcrumbLibrary: "Terms Library",
  pronunciation: "Pronunciation",
  playUs: "Play US pronunciation",
  playUk: "Play UK pronunciation",
  audioPending: "Audio pending",
  audioFailed: "The recording could not be played. Check your connection and try again.",
  learningStatus: "Learning Status",
  definition: "Definition",
  spanishEquivalent: "Spanish Equivalent",
  commonTranslation: "Common Translation",
  civilLaw: "Civil Law Equivalent",
  legalSystemNote: "Legal System Note",
  directEquivalent: "Direct terminological equivalent",
  functionalEquivalent: "Functional equivalent",
  speakerAlert: "Spanish-Speaker Alert",
  useItWith: "Use It With",
  inContext: "In Context",
  realWorld: "Real-World Example",
  usVariant: "US usage",
  ukVariant: "UK usage",
  takeQuizToMaster: "Take the quiz",
  masteredDone: "Mastered",
  addToLibrary: "Add to My Library",
  inMyLibrary: "In My Library",
  nextTerm: "Next Term: {term}",
  previousTerm: "Previous Term",
  nextTermShort: "Next Term",
  quickQuiz: "Quick Quiz",
  oneOfOne: "1 of 1",
  checkAnswer: "Check Answer",
  tryAgain: "Try again",
  correct: "Correct!",
  incorrect: "Not quite.",
  noQuiz: "This term has no quiz yet, so it cannot be published or mastered.",
  yourProgress: "Your Progress",
  understanding: "Understanding",
  progressNew: "You have not studied this term yet. Reading it moves it to Learning.",
  progressLearning: "You've marked this term as Learning. Answer the quiz correctly to master it.",
  progressMastered: "You mastered this term. Attempts: {n}.",
  relatedTerms: "Related Terms",
  viewAllIn: "View all in {category}",
  source: "Source of truth",
  sourceMcd: "MCD workbook",
  sourceEditorial: "Editorial version",
  sourceReviewed: "Last reviewed",
  sourceStatus: "MCD status",
  attempts: "Attempts",
  termNotFound: "This term is not available.",
  termNotFoundBody: "It may be unpublished or the link is wrong.",
  backToLibrary: "Back to Terms Library",
  // quizzes
  quizTitle: "Quiz & Progress",
  quizLead: "Test your knowledge and track your mastery over legal terms.",
  quizAccuracy: "Quiz Accuracy",
  quizzesCompleted: "Quizzes Completed",
  currentStreak: "Current Streak",
  termsMastered: "Terms Mastered",
  days: "Days",
  day: "Day",
  best: "Best: {n} days",
  ofQuizzed: "quizzed terms",
  totalAttempts: "attempts",
  activeQuiz: "Active Quiz",
  questionOf: "Question {i} of {n}",
  quizFor: "{category} Quiz",
  allQuiz: "Mixed Quiz",
  endQuiz: "End Quiz",
  nextQuestion: "Next Question",
  finish: "Finish",
  sessionDone: "Session complete",
  sessionSummary: "{correct} of {n} correct. Mastered terms stay mastered; the others remain in Learning.",
  startAgain: "Start again",
  noQuizzes: "No quizzes available yet. Quizzes appear with published terms.",
  recentHistory: "Recent Quiz History",
  viewAll: "View All",
  quiz: "Quiz",
  score: "Attempts",
  date: "Date",
  category: "Category",
  status: "Status",
  passed: "Passed",
  review: "Review",
  noHistory: "No quiz attempts yet.",
  recommended: "Recommended Practice",
  recommendedLead: "Focus on areas to improve your mastery.",
  needsPractice: "Needs Practice",
  goodProgress: "Good Progress",
  complete: "Complete",
  mastery: "Mastery: {pct}%",
  practiceNow: "Practice Now",
  overallMastery: "Overall Mastery",
  masteryWord: "Mastery",
  keepGoing: "Great progress! Keep practicing to strengthen your understanding.",
  startHint: "Open a term and pass its quiz to start building mastery.",
  masterySnapshot: "Mastery Snapshot",
  recentAchievements: "Recent Achievements",
  categoryAccuracy: "Category Mastery",
  fullReport: "View Full Report",
  // progress
  progressTitle: "My Progress",
  progressLead: "Track your learning journey and see how you're improving.",
  termsStudied: "Terms Studied",
  favourites: "Saved Terms",
  ofTotal: "of {n} available",
  learningActivity: "Learning Activity",
  lastWeeks: "Last 6 weeks",
  legendTerms: "Terms Studied",
  legendQuizzes: "Quiz Attempts",
  byCategory: "Progress by Category",
  viewCategories: "View all categories",
  streakGood: "Great job! Keep it up!",
  photoCardTag: "Study anywhere",
  photoCardTitle: "Five minutes between hearings is enough for one term",
  quizPhotoTag: "Before you test",
  quizPhotoTitle: "Reread the term card, then answer without looking",
  detailPhotoTag: "Keep going",
  detailPhotoTitle: "Take a mixed quiz on everything you have opened",
  categoriesHeroTag: "MCD v1.3.81 · Three canonical categories",
  categoriesHeroTitle: "Every term belongs to exactly one category, as approved in the Master Content Database",
  adminBannerTag: "Owner console",
  adminBannerTitle: "Import, review and publish, in that order",
  searchAll: "See all results for “{q}”",
  reviewMissed: "Review the {n} you missed",
  termPosition: "Term {i} of {n}",
  reportProblem: "Report a problem with this term",
  reportWhat: "What is wrong?",
  reportKind_content: "Definition or example",
  reportKind_translation: "Spanish equivalent",
  reportKind_audio: "Audio",
  reportKind_quiz: "Quiz question",
  reportKind_other: "Something else",
  reportDetail: "Tell us more",
  reportPlaceholder: "What did you expect, and what did you see?",
  reportSend: "Send report",
  reportSent: "Thanks — your report reached the studio.",
  reportFailed: "The report could not be sent. Try again from Help & Support.",
  kbdPick: "pick an answer",
  kbdCheck: "check",
  kbdNext: "next",
  sortBy: "Sort",
  viewGrid: "Grid view",
  viewList: "List view",
  sortCurriculum: "Curriculum order",
  sortAz: "A → Z",
  sortZa: "Z → A",
  sortRecent: "Recently studied",
  sortAttempts: "Most practised",
  filteredCount: "{n} matching terms",
  clearFilters: "Clear filters",
  emptySearchBody: "Try a shorter word, the Spanish equivalent, or remove a filter.",
  checkEyebrow: "Getting started",
  checkTitle: "{done} of {n} done",
  checkAllDone: "You are all set up",
  checkDismiss: "Hide this",
  checkOpen: "Open your first term",
  checkQuiz: "Answer a quiz question",
  checkSave: "Save a term to My Library",
  checkVerify: "Verify your email address",
  checkMaster: "Master your first term",
  dashGoodMorning: "Good morning, {name}",
  dashGoodAfternoon: "Good afternoon, {name}",
  dashGoodEvening: "Good evening, {name}",
  dashLead: "Five minutes today keeps the streak alive. Here is what to work on.",
  dashLeadOwner: "Your workspace as a learner. Drafts appear here too, marked as such.",
  dashSessionTag: "Today's 5-minute session",
  dashSessionTitle: "{n} terms picked for you",
  dashSessionBody: "Terms you are still learning first, then new ones from the curriculum.",
  dashStartSession: "Start with the first term",
  dashQuizThem: "Quiz me on these",
  dashSessionDone: "Nothing left to review today — every term is mastered. Explore the library or retake a quiz.",
  dashContinue: "Continue where you left off",
  dashContinueEmpty: "You have not opened a term yet.",
  dashOpenTerm: "Open term",
  dashStreak: "Streak",
  dashStreakBody: "{n} days in a row",
  dashStreakOne: "1 day — keep it going",
  dashStreakZero: "No streak yet",
  dashMastery: "Mastery",
  dashMasteryBody: "{m} of {n} terms mastered",
  dashSaved: "My Library",
  dashSavedBody: "{n} saved terms",
  dashByCategory: "Your categories",
  dashSeeProgress: "Full progress report",
  dashNewTermsHint: "New terms are added to the curriculum every month.",
  openMenu: "Open menu",
  closeMenu: "Close menu",
  onThisPage: "On this page",
  lastUpdated: "Last updated",
  toastWelcome: "Welcome back, {name}",
  toastFavAdded: "Added to My Library",
  toastFavRemoved: "Removed from My Library",
  toastProfileSaved: "Profile saved",
  // account tabs: preferences / security / notifications
  prefsTitle: "Preferences",
  prefsLead: "Language and privacy choices for this account.",
  prefsLanguageBody: "Applies to menus, labels and messages. Legal terms stay in English.",
  prefsPrivacyNote: "Saved to your account. Legal English 5 never shares your data with third parties; this switch records your choice.",
  prefsDataTitle: "Your data",
  prefsDataBody: "Download everything Legal English 5 stores about you, or read how it is protected.",
  securityTitle: "Security",
  securityLead: "Sign-in details and account controls.",
  emailVerification: "Email verification",
  emailVerifiedBody: "Your email is verified. Password resets and receipts go to this address.",
  emailUnverifiedBody: "Verify your email to secure password resets. The code is in the Alpha Inbox.",
  openInbox: "Open inbox",
  changeEmailBody: "Email changes go through support so the account stays yours.",
  contactSupport: "Contact support",
  dangerZone: "Password and account controls",
  notificationsTitle: "Notifications",
  notificationsLead: "Choose which messages you want to receive.",
  notifStudyReminders: "Study reminders",
  notifStudyRemindersBody: "A short nudge to review terms you have not opened for a week.",
  notifProgress: "Progress summaries",
  notifProgressBody: "A weekly note with terms studied, quiz accuracy and what to review next.",
  notifBilling: "Billing receipts",
  notifBillingBody: "Payment confirmations and renewal reminders. These are always sent.",
  notifInbox: "Alpha Inbox notices",
  notifInboxBody: "Show pending verification codes on the Help page while the alpha runs.",
  notifAlways: "Always on",
  toggleOn: "On",
  toggleOff: "Off",
  prefsSaved: "Preference saved to your account.",
  prefsFailed: "The preference could not be saved. Try again.",
  notifEmailSoon: "Email delivery starts with launch; your choice is saved now.",
  toastPhotoSaved: "Profile photo updated",
  toastPhotoRemoved: "Profile photo removed",
  photoFailed: "The photo could not be saved. Try again.",
  photoChange: "Change photo",
  photoAdd: "Add photo",
  photoRemove: "Remove photo",
  photoSave: "Save photo",
  photoCancel: "Discard",
  photoHint: "JPG, PNG or WebP. Cropped to a square and resized to 256 px.",
  photoTooLarge: "That file is too large. Choose an image under 10 MB.",
  photoNotImage: "Choose a JPG, PNG or WebP image.",
  photoOf: "Profile photo of {name}",
  toastPasswordChanged: "Password changed",
  toastPublished: "{id} is now visible to learners",
  toastUnpublished: "{id} hidden from learners",
  toastImported: "Import committed · {n} terms written",
  streakStart: "Study today to start a streak.",
  longest: "Longest streak: {n} days",
  recentActivity: "Recent Activity",
  noActivity: "No activity yet. Open a term to begin.",
  achievements: "Achievements",
  achieved: "Completed",
  today: "Today",
  yesterday: "Yesterday",
  mastered: "Mastered \u201c{term}\u201d",
  attempted: "Quiz attempt: {term}",
  studied: "Studied \u201c{term}\u201d",
  savedTerm: "Saved \u201c{term}\u201d",
  achFirstSteps: "First Steps",
  achFirstStepsBody: "Study 10 terms",
  achQuizMaster: "Quiz Master",
  achQuizMasterBody: "Complete 10 quizzes",
  achConsistent: "Consistent Learner",
  achConsistentBody: "Maintain a 7-day streak",
  achFirstMastery: "First Mastery",
  achFirstMasteryBody: "Master your first term",
  achChampion: "Category Champion",
  achChampionBody: "Master every term in a category",
  // account
  accountTitle: "Account",
  accountLead: "Manage your profile, preferences, and account settings.",
  tabProfile: "Profile",
  tabPreferences: "Preferences",
  tabSecurity: "Security",
  tabNotifications: "Notifications",
  profileInfo: "Profile Information",
  editProfile: "Edit Profile",
  saveProfile: "Save",
  cancel: "Cancel",
  fullName: "Full Name",
  email: "Email Address",
  role: "Role",
  memberSince: "Member since",
  emailStatus: "Email status",
  verified: "Verified",
  unverified: "Not verified",
  language: "Interface language",
  joined: "Joined {date}",
  accountSettings: "Account Settings",
  changePassword: "Change Password",
  changePasswordBody: "Update your password to keep your account secure.",
  currentPassword: "Current password",
  newPassword: "New password (8+ characters)",
  passwordChanged: "Password updated.",
  deactivate: "Deactivate Account",
  deactivateBody: "Pause your account without deleting anything. Reactivate any time by logging in.",
  deactivateAction: "Deactivate",
  deleteAccount: "Delete Account",
  deleteBody: "Permanently delete your account and all data.",
  deleteAction: "Delete",
  deleteConfirm: "Delete your account and all progress permanently? This cannot be undone.",
  profileSaved: "Profile updated.",
  avgAttempts: "Attempts per term",
  viewFullProgress: "View Full Progress",
  subscription: "Subscription",
  plan: "Plan",
  planTrial: "7-day trial",
  planMonthly: "Monthly plan",
  planAnnual: "Annual plan",
  planNone: "No plan yet",
  trialEnds: "Trial ends",
  accessUntil: "Access until",
  periodEnd: "Current period ends",
  manageSubscription: "Manage Subscription",
  // categories / my library
  categoriesTitle: "Categories",
  categoriesLead: "The three canonical categories of the MCD. Pick one to filter the library.",
  browse: "Browse terms",
  myLibraryTitle: "My Library",
  myLibraryLead: "Terms you saved with the bookmark.",
  emptyMyLibrary: "Nothing saved yet. Use the bookmark on any term to keep it here.",
  // how it works
  howEyebrow: "Your learning loop",
  howTitle: "How It Works",
  howLead: "Legal English 5 is designed to help you learn, practice, and master legal terms in a simple and effective way.",
  howStepsLabel: "How Legal English 5 works",
  howStep1Title: "Explore Terms",
  howStep1Body: "Browse or search the library of legal terms. Each term includes a clear definition, the Spanish and civil-law equivalents and a real-world example.",
  howStep1Cta: "Open the library",
  howStep2Title: "Learn & Understand",
  howStep2Body: "Read the explanation, listen to the pronunciation, see the term used in context and save the important ones to My Library.",
  howStep2Cta: "Open a term",
  howStep3Title: "Practice with Quizzes",
  howStep3Body: "Test yourself with multiple-choice questions. A correct answer marks the term Mastered; a wrong one sends it back to Learning so you see it again.",
  howStep3Cta: "Start a quiz",
  howStep4Title: "Track Your Progress",
  howStep4Body: "Follow your streak, mastery by category and quiz accuracy. Every number comes from your own study record.",
  howStep4Cta: "See progress",
  howStep5Title: "Master Legal English",
  howStep5Body: "Stay consistent with a five-minute daily session and use Legal English with confidence in real situations.",
  howStep5Cta: "Today's session",
  howStepDone: "Done",
  howStepTodo: "Not yet",
  howStat1: "{n} of {total} terms opened",
  howStat2: "{n} saved to My Library",
  howStat3: "{n} quiz answers",
  howStat4: "{n}-day streak",
  howStat5: "{n} of {total} mastered",
  howResultTitle: "Built for real results",
  howResultBody: "A structured curriculum, expert-reviewed content and honest tracking help you build knowledge that lasts.",
  howStartLearning: "Start Learning",
  howContinueLearning: "Continue Learning",
  howSupportLine: "Have questions? We're here to help you succeed.",
  howContactSupport: "Contact Support",
  howWhyTitle: "Why Learn with Legal English 5?",
  howWhy1Title: "Expert-Reviewed Content",
  howWhy1Body: "Every term and example is written and reviewed by a practising lawyer.",
  howWhy2Title: "Practical & Relevant",
  howWhy2Body: "Learn the vocabulary of contracts, corporate law and employment law with examples from real situations.",
  howWhy3Title: "Learn at Your Pace",
  howWhy3Body: "Study anytime, anywhere. Five minutes a day is enough to keep your streak alive.",
  howWhy4Title: "Secure & Reliable",
  howWhy4Body: "Your progress and personal data are protected and you can download them at any time.",
  howHelpTitle: "Need More Help?",
  howHelpBody: "Check the Help Center or contact the team with any question.",
  howHelpCta: "Visit Help Center",
  howProgressEmpty: "Open your first term and this card starts filling in.",
  // keyboard shortcuts
  shortcutsButton: "Keyboard shortcuts",
  shortcutsTitle: "Keyboard shortcuts",
  shortcutsLead: "Work faster without leaving the keyboard. Press ? at any time to open this list.",
  shortcutsAnywhere: "Anywhere",
  shortcutsTerm: "On a term",
  shortcutsQuiz: "In a quiz",
  shortcutSearch: "Focus the search box",
  shortcutSuggest: "Move through search suggestions",
  shortcutOpen: "Open the highlighted suggestion",
  shortcutHelp: "Show this list",
  shortcutClose: "Close menus and dialogs",
  shortcutTermNav: "Previous / next term",
  shortcutSave: "Save or unsave in My Library",
  shortcutQuizPick: "Pick an answer",
  shortcutQuizCheck: "Check the answer, then go to the next question",
};

const es: typeof en = {
  navHome: "Inicio",
  brandHome: "Legal English 5 — ir a la página de inicio del sitio",
  navLibrary: "Biblioteca de términos",
  navCategories: "Categorías",
  navProgress: "Progreso",
  navQuizzes: "Quizzes",
  navMyLibrary: "Mi biblioteca",
  navAccount: "Cuenta",
  navBilling: "Facturación",
  navHelp: "Ayuda y soporte",
  navSettings: "Ajustes",
  navHowItWorks: "Cómo funciona",
  navAdmin: "Consola",
  signOut: "Cerrar sesión",
  searchPlaceholder: "Buscar términos, categorías o contenido...",
  notifications: "Notificaciones",
  upgradeNow: "Mejorar plan",
  manageAccess: "Gestionar acceso",
  owner: "Titular",
  learner: "Alumno",
  opening: "Abriendo el estudio…",
  loadFailed: "No pudimos conectar con el servidor. Revisa tu conexión e inténtalo de nuevo.",
  retry: "Intentar de nuevo",
  accessPaused: "Acceso en pausa",
  accessInactive: "Tu prueba o suscripción no está activa.",
  lockedCard: "Renueva tu acceso para leer este término.",
  accessRefresh: "Esta decisión está en el servidor. Recargar el navegador no restablece el acceso.",
  reviewAccess: "Revisar acceso de Mercado Pago",
  deactivatedTitle: "Esta cuenta está desactivada.",
  deactivatedBody: "Pausaste esta cuenta desde Cuenta. No se borró nada: tu contenido y progreso están tal como los dejaste.",
  reactivate: "Reactivar cuenta",
  libraryTitle: "Biblioteca de términos",
  libraryLead: "Explora y domina la terminología jurídica esencial.",
  libraryLeadOwner: "Ves todos los términos del MCD, incluidos borradores. Los alumnos solo ven los Publicados.",
  allTerms: "Todos",
  stateNew: "Nuevo",
  stateLearning: "Aprendiendo",
  stateMastered: "Dominado",
  allCategories: "Todas las categorías",
  termsCount: "{n} términos",
  termsCountOne: "1 término",
  draft: "Borrador",
  saved: "Guardado",
  save: "Guardar",
  emptyLibraryTitle: "Aún no hay términos publicados",
  emptyLibraryBody: "Los términos aparecen aquí cuando la titular los publica (requiere quiz + AudioUS). Approved no es Published.",
  emptySearch: "Ningún término coincide con tu búsqueda.",
  showing: "Mostrando {from}–{to} de {n}",
  perPage: "por página",
  previous: "Anterior",
  next: "Siguiente",
  breadcrumbLibrary: "Biblioteca de términos",
  pronunciation: "Pronunciación",
  playUs: "Reproducir pronunciación US",
  playUk: "Reproducir pronunciación UK",
  audioPending: "Audio pendiente",
  audioFailed: "No se pudo reproducir la grabación. Revisa tu conexión e inténtalo de nuevo.",
  learningStatus: "Estado de aprendizaje",
  definition: "Definición",
  spanishEquivalent: "Equivalente en español",
  commonTranslation: "Traducción habitual",
  civilLaw: "Equivalente en derecho civil",
  legalSystemNote: "Nota de sistema jurídico",
  directEquivalent: "Equivalente terminológico directo",
  functionalEquivalent: "Equivalente funcional",
  speakerAlert: "Alerta para hispanohablantes",
  useItWith: "Se usa con",
  inContext: "En contexto",
  realWorld: "Ejemplo real",
  usVariant: "Uso en EE. UU.",
  ukVariant: "Uso en Reino Unido",
  takeQuizToMaster: "Hacer el quiz",
  masteredDone: "Dominado",
  addToLibrary: "Guardar en Mi biblioteca",
  inMyLibrary: "En Mi biblioteca",
  nextTerm: "Siguiente: {term}",
  previousTerm: "Término anterior",
  nextTermShort: "Término siguiente",
  quickQuiz: "Quiz rápido",
  oneOfOne: "1 de 1",
  checkAnswer: "Comprobar respuesta",
  tryAgain: "Intentar de nuevo",
  correct: "¡Correcto!",
  incorrect: "No es correcto.",
  noQuiz: "Este término aún no tiene quiz, así que no puede publicarse ni dominarse.",
  yourProgress: "Tu progreso",
  understanding: "Comprensión",
  progressNew: "Aún no has estudiado este término. Leerlo lo pasa a Aprendiendo.",
  progressLearning: "Este término está en Aprendiendo. Responde bien el quiz para dominarlo.",
  progressMastered: "Dominaste este término. Intentos: {n}.",
  relatedTerms: "Términos relacionados",
  viewAllIn: "Ver todos en {category}",
  source: "Fuente de verdad",
  sourceMcd: "Libro MCD",
  sourceEditorial: "Versión editorial",
  sourceReviewed: "Última revisión",
  sourceStatus: "Estado MCD",
  attempts: "Intentos",
  termNotFound: "Este término no está disponible.",
  termNotFoundBody: "Puede que no esté publicado o que el enlace sea incorrecto.",
  backToLibrary: "Volver a la biblioteca",
  quizTitle: "Quiz y progreso",
  quizLead: "Pon a prueba tus conocimientos y sigue tu dominio de los términos.",
  quizAccuracy: "Precisión en quizzes",
  quizzesCompleted: "Quizzes completados",
  currentStreak: "Racha actual",
  termsMastered: "Términos dominados",
  days: "días",
  day: "día",
  best: "Mejor: {n} días",
  ofQuizzed: "términos evaluados",
  totalAttempts: "intentos",
  activeQuiz: "Quiz activo",
  questionOf: "Pregunta {i} de {n}",
  quizFor: "Quiz de {category}",
  allQuiz: "Quiz mixto",
  endQuiz: "Terminar",
  nextQuestion: "Siguiente pregunta",
  finish: "Finalizar",
  sessionDone: "Sesión completada",
  sessionSummary: "{correct} de {n} correctas. Los términos dominados se mantienen; el resto sigue en Aprendiendo.",
  startAgain: "Empezar de nuevo",
  noQuizzes: "Aún no hay quizzes. Aparecen con los términos publicados.",
  recentHistory: "Historial reciente",
  viewAll: "Ver todo",
  quiz: "Quiz",
  score: "Intentos",
  date: "Fecha",
  category: "Categoría",
  status: "Estado",
  passed: "Aprobado",
  review: "Repasar",
  noHistory: "Todavía no hay intentos.",
  recommended: "Práctica recomendada",
  recommendedLead: "Enfócate en las áreas que más lo necesitan.",
  needsPractice: "Necesita práctica",
  goodProgress: "Buen avance",
  complete: "Completa",
  mastery: "Dominio: {pct}%",
  practiceNow: "Practicar",
  overallMastery: "Dominio general",
  masteryWord: "Dominio",
  keepGoing: "¡Buen progreso! Sigue practicando para afianzar lo aprendido.",
  startHint: "Abre un término y aprueba su quiz para empezar a construir dominio.",
  masterySnapshot: "Resumen de dominio",
  recentAchievements: "Logros recientes",
  categoryAccuracy: "Dominio por categoría",
  fullReport: "Ver informe completo",
  progressTitle: "Mi progreso",
  progressLead: "Sigue tu camino de aprendizaje y mira cómo mejoras.",
  termsStudied: "Términos estudiados",
  favourites: "Términos guardados",
  ofTotal: "de {n} disponibles",
  learningActivity: "Actividad de aprendizaje",
  lastWeeks: "Últimas 6 semanas",
  legendTerms: "Términos estudiados",
  legendQuizzes: "Intentos de quiz",
  byCategory: "Progreso por categoría",
  viewCategories: "Ver todas las categorías",
  streakGood: "¡Muy bien! Sigue así.",
  photoCardTag: "Estudia donde estés",
  photoCardTitle: "Cinco minutos entre audiencias bastan para un término",
  quizPhotoTag: "Antes de evaluarte",
  quizPhotoTitle: "Relee la ficha del término y responde sin mirar",
  detailPhotoTag: "Sigue avanzando",
  detailPhotoTitle: "Haz un quiz mixto con todo lo que has abierto",
  categoriesHeroTag: "MCD v1.3.81 · Tres categorías canónicas",
  categoriesHeroTitle: "Cada término pertenece a una sola categoría, tal como se aprobó en el Master Content Database",
  adminBannerTag: "Consola de la propietaria",
  adminBannerTitle: "Importar, revisar y publicar, en ese orden",
  searchAll: "Ver todos los resultados de “{q}”",
  reviewMissed: "Repasa los {n} que fallaste",
  termPosition: "Término {i} de {n}",
  reportProblem: "Reportar un problema con este término",
  reportWhat: "¿Qué está mal?",
  reportKind_content: "Definición o ejemplo",
  reportKind_translation: "Equivalente en español",
  reportKind_audio: "Audio",
  reportKind_quiz: "Pregunta del quiz",
  reportKind_other: "Otra cosa",
  reportDetail: "Cuéntanos más",
  reportPlaceholder: "¿Qué esperabas y qué viste?",
  reportSend: "Enviar reporte",
  reportSent: "Gracias, tu reporte llegó al estudio.",
  reportFailed: "No se pudo enviar el reporte. Inténtalo desde Ayuda y soporte.",
  kbdPick: "elige una respuesta",
  kbdCheck: "comprobar",
  kbdNext: "siguiente",
  sortBy: "Ordenar",
  viewGrid: "Vista en cuadrícula",
  viewList: "Vista en lista",
  sortCurriculum: "Orden del plan",
  sortAz: "A → Z",
  sortZa: "Z → A",
  sortRecent: "Estudiados recientemente",
  sortAttempts: "Más practicados",
  filteredCount: "{n} términos coinciden",
  clearFilters: "Quitar filtros",
  emptySearchBody: "Prueba una palabra más corta, el equivalente en español o quita un filtro.",
  checkEyebrow: "Primeros pasos",
  checkTitle: "{done} de {n} completados",
  checkAllDone: "Ya tienes todo listo",
  checkDismiss: "Ocultar",
  checkOpen: "Abre tu primer término",
  checkQuiz: "Responde una pregunta de quiz",
  checkSave: "Guarda un término en Mi biblioteca",
  checkVerify: "Verifica tu correo electrónico",
  checkMaster: "Domina tu primer término",
  dashGoodMorning: "Buenos días, {name}",
  dashGoodAfternoon: "Buenas tardes, {name}",
  dashGoodEvening: "Buenas noches, {name}",
  dashLead: "Cinco minutos hoy mantienen viva la racha. Esto es lo que toca trabajar.",
  dashLeadOwner: "Tu espacio como estudiante. Los borradores también aparecen aquí, marcados como tal.",
  dashSessionTag: "Sesión de 5 minutos de hoy",
  dashSessionTitle: "{n} términos elegidos para ti",
  dashSessionBody: "Primero los términos que aún estás aprendiendo, luego los nuevos del plan.",
  dashStartSession: "Empezar con el primer término",
  dashQuizThem: "Ponme a prueba con estos",
  dashSessionDone: "No queda nada por repasar hoy: todos los términos están dominados. Explora la biblioteca o repite un quiz.",
  dashContinue: "Continúa donde lo dejaste",
  dashContinueEmpty: "Aún no has abierto ningún término.",
  dashOpenTerm: "Abrir término",
  dashStreak: "Racha",
  dashStreakBody: "{n} días seguidos",
  dashStreakOne: "1 día — sigue así",
  dashStreakZero: "Aún sin racha",
  dashMastery: "Dominio",
  dashMasteryBody: "{m} de {n} términos dominados",
  dashSaved: "Mi biblioteca",
  dashSavedBody: "{n} términos guardados",
  dashByCategory: "Tus categorías",
  dashSeeProgress: "Informe completo de progreso",
  dashNewTermsHint: "Cada mes se agregan nuevos términos al plan.",
  openMenu: "Abrir menú",
  closeMenu: "Cerrar menú",
  onThisPage: "En esta página",
  lastUpdated: "Última actualización",
  toastWelcome: "Bienvenido de nuevo, {name}",
  toastFavAdded: "Añadido a Mi biblioteca",
  toastFavRemoved: "Quitado de Mi biblioteca",
  toastProfileSaved: "Perfil guardado",
  prefsTitle: "Preferencias",
  prefsLead: "Idioma y opciones de privacidad de esta cuenta.",
  prefsLanguageBody: "Se aplica a menús, etiquetas y mensajes. Los términos legales se mantienen en inglés.",
  prefsPrivacyNote: "Se guarda en tu cuenta. Legal English 5 nunca comparte tus datos con terceros; este interruptor registra tu elección.",
  prefsDataTitle: "Tus datos",
  prefsDataBody: "Descarga todo lo que Legal English 5 guarda sobre ti o lee cómo se protege.",
  securityTitle: "Seguridad",
  securityLead: "Datos de acceso y controles de la cuenta.",
  emailVerification: "Verificación del correo",
  emailVerifiedBody: "Tu correo está verificado. Los restablecimientos de contraseña y los recibos llegan a esta dirección.",
  emailUnverifiedBody: "Verifica tu correo para asegurar el restablecimiento de contraseña. El código está en la bandeja Alpha.",
  openInbox: "Abrir bandeja",
  changeEmailBody: "Los cambios de correo se gestionan con soporte para que la cuenta siga siendo tuya.",
  contactSupport: "Contactar soporte",
  dangerZone: "Contraseña y controles de la cuenta",
  notificationsTitle: "Notificaciones",
  notificationsLead: "Elige qué mensajes quieres recibir.",
  notifStudyReminders: "Recordatorios de estudio",
  notifStudyRemindersBody: "Un aviso breve para repasar los términos que no has abierto en una semana.",
  notifProgress: "Resumen de progreso",
  notifProgressBody: "Una nota semanal con términos estudiados, precisión en quizzes y qué repasar.",
  notifBilling: "Recibos de pago",
  notifBillingBody: "Confirmaciones de pago y avisos de renovación. Siempre se envían.",
  notifInbox: "Avisos de la bandeja Alpha",
  notifInboxBody: "Mostrar códigos de verificación pendientes en Ayuda mientras dure el alpha.",
  notifAlways: "Siempre activo",
  toggleOn: "Activado",
  toggleOff: "Desactivado",
  prefsSaved: "Preferencia guardada en tu cuenta.",
  prefsFailed: "No se pudo guardar la preferencia. Inténtalo de nuevo.",
  notifEmailSoon: "El envío de correos empieza con el lanzamiento; tu elección queda guardada desde ahora.",
  toastPhotoSaved: "Foto de perfil actualizada",
  toastPhotoRemoved: "Foto de perfil eliminada",
  photoFailed: "No se pudo guardar la foto. Inténtalo de nuevo.",
  photoChange: "Cambiar foto",
  photoAdd: "Añadir foto",
  photoRemove: "Quitar foto",
  photoSave: "Guardar foto",
  photoCancel: "Descartar",
  photoHint: "JPG, PNG o WebP. Se recorta en cuadrado y se reduce a 256 px.",
  photoTooLarge: "El archivo es demasiado grande. Elige una imagen de menos de 10 MB.",
  photoNotImage: "Elige una imagen JPG, PNG o WebP.",
  photoOf: "Foto de perfil de {name}",
  toastPasswordChanged: "Contraseña cambiada",
  toastPublished: "{id} ya es visible para los estudiantes",
  toastUnpublished: "{id} oculto para los estudiantes",
  toastImported: "Importación confirmada · {n} términos escritos",
  streakStart: "Estudia hoy para iniciar una racha.",
  longest: "Racha más larga: {n} días",
  recentActivity: "Actividad reciente",
  noActivity: "Sin actividad todavía. Abre un término para empezar.",
  achievements: "Logros",
  achieved: "Completado",
  today: "Hoy",
  yesterday: "Ayer",
  mastered: "Dominaste \u201c{term}\u201d",
  attempted: "Intento de quiz: {term}",
  studied: "Estudiaste \u201c{term}\u201d",
  savedTerm: "Guardaste \u201c{term}\u201d",
  achFirstSteps: "Primeros pasos",
  achFirstStepsBody: "Estudia 10 términos",
  achQuizMaster: "Maestro del quiz",
  achQuizMasterBody: "Completa 10 quizzes",
  achConsistent: "Constancia",
  achConsistentBody: "Mantén una racha de 7 días",
  achFirstMastery: "Primer dominio",
  achFirstMasteryBody: "Domina tu primer término",
  achChampion: "Campeón de categoría",
  achChampionBody: "Domina todos los términos de una categoría",
  accountTitle: "Cuenta",
  accountLead: "Gestiona tu perfil, preferencias y ajustes de la cuenta.",
  tabProfile: "Perfil",
  tabPreferences: "Preferencias",
  tabSecurity: "Seguridad",
  tabNotifications: "Notificaciones",
  profileInfo: "Información del perfil",
  editProfile: "Editar perfil",
  saveProfile: "Guardar",
  cancel: "Cancelar",
  fullName: "Nombre completo",
  email: "Correo electrónico",
  role: "Rol",
  memberSince: "Miembro desde",
  emailStatus: "Estado del correo",
  verified: "Verificado",
  unverified: "Sin verificar",
  language: "Idioma de la interfaz",
  joined: "Desde {date}",
  accountSettings: "Ajustes de la cuenta",
  changePassword: "Cambiar contraseña",
  changePasswordBody: "Actualiza tu contraseña para mantener la cuenta segura.",
  currentPassword: "Contraseña actual",
  newPassword: "Nueva contraseña (8+ caracteres)",
  passwordChanged: "Contraseña actualizada.",
  deactivate: "Desactivar cuenta",
  deactivateBody: "Pausa tu cuenta sin borrar nada. Reactívala cuando quieras al iniciar sesión.",
  deactivateAction: "Desactivar",
  deleteAccount: "Eliminar cuenta",
  deleteBody: "Elimina tu cuenta y todos tus datos de forma permanente.",
  deleteAction: "Eliminar",
  deleteConfirm: "¿Eliminar tu cuenta y todo tu progreso de forma permanente? No se puede deshacer.",
  profileSaved: "Perfil actualizado.",
  avgAttempts: "Intentos por término",
  viewFullProgress: "Ver progreso completo",
  subscription: "Suscripción",
  plan: "Plan",
  planTrial: "Prueba de 7 días",
  planMonthly: "Plan mensual",
  planAnnual: "Plan anual",
  planNone: "Sin plan aún",
  trialEnds: "La prueba termina",
  accessUntil: "Acceso hasta",
  periodEnd: "Fin del periodo actual",
  manageSubscription: "Gestionar suscripción",
  categoriesTitle: "Categorías",
  categoriesLead: "Las tres categorías canónicas del MCD. Elige una para filtrar la biblioteca.",
  browse: "Ver términos",
  myLibraryTitle: "Mi biblioteca",
  myLibraryLead: "Términos que guardaste con el marcador.",
  emptyMyLibrary: "Nada guardado todavía. Usa el marcador en cualquier término para tenerlo aquí.",
  // how it works
  howEyebrow: "Tu ciclo de aprendizaje",
  howTitle: "Cómo funciona",
  howLead: "Legal English 5 está diseñado para ayudarte a aprender, practicar y dominar términos jurídicos de forma sencilla y eficaz.",
  howStepsLabel: "Cómo funciona Legal English 5",
  howStep1Title: "Explora los términos",
  howStep1Body: "Navega o busca en la biblioteca de términos jurídicos. Cada término incluye una definición clara, los equivalentes en español y en derecho civil y un ejemplo real.",
  howStep1Cta: "Abrir la biblioteca",
  howStep2Title: "Aprende y comprende",
  howStep2Body: "Lee la explicación, escucha la pronunciación, mira el término en contexto y guarda los importantes en Mi biblioteca.",
  howStep2Cta: "Abrir un término",
  howStep3Title: "Practica con quizzes",
  howStep3Body: "Ponte a prueba con preguntas de opción múltiple. Una respuesta correcta marca el término como Dominado; una incorrecta lo devuelve a Aprendiendo para que lo vuelvas a ver.",
  howStep3Cta: "Empezar un quiz",
  howStep4Title: "Sigue tu progreso",
  howStep4Body: "Revisa tu racha, el dominio por categoría y la precisión en quizzes. Cada número sale de tu propio registro de estudio.",
  howStep4Cta: "Ver progreso",
  howStep5Title: "Domina el inglés jurídico",
  howStep5Body: "Mantén la constancia con una sesión diaria de cinco minutos y usa el inglés jurídico con confianza en situaciones reales.",
  howStep5Cta: "Sesión de hoy",
  howStepDone: "Hecho",
  howStepTodo: "Pendiente",
  howStat1: "{n} de {total} términos abiertos",
  howStat2: "{n} guardados en Mi biblioteca",
  howStat3: "{n} respuestas de quiz",
  howStat4: "Racha de {n} días",
  howStat5: "{n} de {total} dominados",
  howResultTitle: "Hecho para resultados reales",
  howResultBody: "Un currículo estructurado, contenido revisado por expertos y un seguimiento honesto te ayudan a construir conocimiento duradero.",
  howStartLearning: "Empezar a aprender",
  howContinueLearning: "Seguir aprendiendo",
  howSupportLine: "¿Tienes preguntas? Estamos aquí para ayudarte.",
  howContactSupport: "Contactar soporte",
  howWhyTitle: "¿Por qué aprender con Legal English 5?",
  howWhy1Title: "Contenido revisado por expertos",
  howWhy1Body: "Cada término y ejemplo está escrito y revisado por un abogado en ejercicio.",
  howWhy2Title: "Práctico y relevante",
  howWhy2Body: "Aprende el vocabulario de contratos, derecho corporativo y derecho laboral con ejemplos de situaciones reales.",
  howWhy3Title: "A tu ritmo",
  howWhy3Body: "Estudia cuando y donde quieras. Cinco minutos al día bastan para mantener la racha.",
  howWhy4Title: "Seguro y confiable",
  howWhy4Body: "Tu progreso y tus datos personales están protegidos y puedes descargarlos en cualquier momento.",
  howHelpTitle: "¿Necesitas más ayuda?",
  howHelpBody: "Consulta el Centro de ayuda o escribe al equipo con cualquier duda.",
  howHelpCta: "Ir al Centro de ayuda",
  howProgressEmpty: "Abre tu primer término y esta tarjeta empieza a llenarse.",
  // keyboard shortcuts
  shortcutsButton: "Atajos de teclado",
  shortcutsTitle: "Atajos de teclado",
  shortcutsLead: "Trabaja más rápido sin soltar el teclado. Pulsa ? en cualquier momento para abrir esta lista.",
  shortcutsAnywhere: "En cualquier página",
  shortcutsTerm: "En un término",
  shortcutsQuiz: "En un quiz",
  shortcutSearch: "Ir al buscador",
  shortcutSuggest: "Moverse por las sugerencias",
  shortcutOpen: "Abrir la sugerencia marcada",
  shortcutHelp: "Mostrar esta lista",
  shortcutClose: "Cerrar menús y ventanas",
  shortcutTermNav: "Término anterior / siguiente",
  shortcutSave: "Guardar o quitar de Mi biblioteca",
  shortcutQuizPick: "Elegir una respuesta",
  shortcutQuizCheck: "Comprobar la respuesta y pasar a la siguiente",
};

export type LearnerKey = keyof typeof en;
const copy: Record<Locale, typeof en> = { en, es };

export function learnerText(locale: Locale, key: LearnerKey, vars?: Record<string, string | number>) {
  let text = copy[locale][key];
  if (vars) for (const [name, value] of Object.entries(vars)) text = text.replaceAll(`{${name}}`, String(value));
  return text;
}
